@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.common.items.recipe;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;