@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.client.renderer.entity;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;