package thebetweenlands.client.model.baked.sundew;

import thebetweenlands.util.QuadBuilder;

/**
 * Procedurally generated geometry from the 1.12.2 Tabula {@code ModelSundew}.
 * Generated by {@code convert_tabula_model_to_quadbuilder.py}.
 */
public final class SundewGeometry {

	private SundewGeometry() {
	}

	public static void build(QuadBuilder builder) {
		//hairs3
		builder.addVertex(0.250625F, 1.689748F, 0.186223F, 4.625F, 10.5F);
		builder.addVertex(0.750625F, 1.689748F, 0.186223F, 5.625F, 10.5F);
		builder.addVertex(0.750625F, 1.555019F, 0.396813F, 5.625F, 12.5F);
		builder.addVertex(0.250625F, 1.555019F, 0.396813F, 4.625F, 12.5F);

		builder.addVertex(0.250625F, 1.555019F, 0.396813F, 4.625F, 12.5F);
		builder.addVertex(0.750625F, 1.555019F, 0.396813F, 5.625F, 12.5F);
		builder.addVertex(0.750625F, 1.689748F, 0.186223F, 5.625F, 10.5F);
		builder.addVertex(0.250625F, 1.689748F, 0.186223F, 4.625F, 10.5F);

		builder.addVertex(0.250625F, 1.952985F, 0.354635F, 7.25F, 10.5F);
		builder.addVertex(0.250625F, 1.818256F, 0.565224F, 7.25F, 12.5F);
		builder.addVertex(0.750625F, 1.818256F, 0.565224F, 6.25F, 12.5F);
		builder.addVertex(0.750625F, 1.952985F, 0.354635F, 6.25F, 10.5F);

		builder.addVertex(0.750625F, 1.952985F, 0.354635F, 6.25F, 10.5F);
		builder.addVertex(0.750625F, 1.818256F, 0.565224F, 6.25F, 12.5F);
		builder.addVertex(0.250625F, 1.818256F, 0.565224F, 7.25F, 12.5F);
		builder.addVertex(0.250625F, 1.952985F, 0.354635F, 7.25F, 10.5F);

		builder.addVertex(0.250625F, 1.555019F, 0.396813F, 5.625F, 10.5F);
		builder.addVertex(0.750625F, 1.555019F, 0.396813F, 6.25F, 10.5F);
		builder.addVertex(0.750625F, 1.818256F, 0.565224F, 6.25F, 8F);
		builder.addVertex(0.250625F, 1.818256F, 0.565224F, 5.625F, 8F);

		builder.addVertex(0.250625F, 1.818256F, 0.565224F, 5.625F, 8F);
		builder.addVertex(0.750625F, 1.818256F, 0.565224F, 6.25F, 8F);
		builder.addVertex(0.750625F, 1.555019F, 0.396813F, 6.25F, 10.5F);
		builder.addVertex(0.250625F, 1.555019F, 0.396813F, 5.625F, 10.5F);

		builder.addVertex(0.250625F, 1.689748F, 0.186223F, 4.625F, 10.5F);
		builder.addVertex(0.250625F, 1.952985F, 0.354635F, 4.625F, 8F);
		builder.addVertex(0.750625F, 1.952985F, 0.354635F, 5.625F, 8F);
		builder.addVertex(0.750625F, 1.689748F, 0.186223F, 5.625F, 10.5F);

		builder.addVertex(0.750625F, 1.689748F, 0.186223F, 5.625F, 10.5F);
		builder.addVertex(0.750625F, 1.952985F, 0.354635F, 5.625F, 8F);
		builder.addVertex(0.250625F, 1.952985F, 0.354635F, 4.625F, 8F);
		builder.addVertex(0.250625F, 1.689748F, 0.186223F, 4.625F, 10.5F);

		builder.addVertex(0.750625F, 1.689748F, 0.186223F, 5.625F, 10.5F);
		builder.addVertex(0.750625F, 1.952985F, 0.354635F, 6.25F, 10.5F);
		builder.addVertex(0.750625F, 1.818256F, 0.565224F, 6.25F, 12.5F);
		builder.addVertex(0.750625F, 1.555019F, 0.396813F, 5.625F, 12.5F);

		builder.addVertex(0.750625F, 1.555019F, 0.396813F, 5.625F, 12.5F);
		builder.addVertex(0.750625F, 1.818256F, 0.565224F, 6.25F, 12.5F);
		builder.addVertex(0.750625F, 1.952985F, 0.354635F, 6.25F, 10.5F);
		builder.addVertex(0.750625F, 1.689748F, 0.186223F, 5.625F, 10.5F);

		builder.addVertex(0.250625F, 1.689748F, 0.186223F, 4.625F, 10.5F);
		builder.addVertex(0.250625F, 1.555019F, 0.396813F, 4.625F, 12.5F);
		builder.addVertex(0.250625F, 1.818256F, 0.565224F, 4F, 12.5F);
		builder.addVertex(0.250625F, 1.952985F, 0.354635F, 4F, 10.5F);

		builder.addVertex(0.250625F, 1.952985F, 0.354635F, 4F, 10.5F);
		builder.addVertex(0.250625F, 1.818256F, 0.565224F, 4F, 12.5F);
		builder.addVertex(0.250625F, 1.555019F, 0.396813F, 4.625F, 12.5F);
		builder.addVertex(0.250625F, 1.689748F, 0.186223F, 4.625F, 10.5F);

		//hairs4
		builder.addVertex(0.2825F, 1.659131F, 0.182849F, 4.25F, 5.5F);
		builder.addVertex(0.72F, 1.659131F, 0.182849F, 5.125F, 5.5F);
		builder.addVertex(0.72F, 1.6988F, 0.429682F, 5.125F, 7.5F);
		builder.addVertex(0.2825F, 1.6988F, 0.429682F, 4.25F, 7.5F);

		builder.addVertex(0.2825F, 1.6988F, 0.429682F, 4.25F, 7.5F);
		builder.addVertex(0.72F, 1.6988F, 0.429682F, 5.125F, 7.5F);
		builder.addVertex(0.72F, 1.659131F, 0.182849F, 5.125F, 5.5F);
		builder.addVertex(0.2825F, 1.659131F, 0.182849F, 4.25F, 5.5F);

		builder.addVertex(0.2825F, 1.905964F, 0.14318F, 6.5F, 5.5F);
		builder.addVertex(0.2825F, 1.945633F, 0.390013F, 6.5F, 7.5F);
		builder.addVertex(0.72F, 1.945633F, 0.390013F, 5.625F, 7.5F);
		builder.addVertex(0.72F, 1.905964F, 0.14318F, 5.625F, 5.5F);

		builder.addVertex(0.72F, 1.905964F, 0.14318F, 5.625F, 5.5F);
		builder.addVertex(0.72F, 1.945633F, 0.390013F, 5.625F, 7.5F);
		builder.addVertex(0.2825F, 1.945633F, 0.390013F, 6.5F, 7.5F);
		builder.addVertex(0.2825F, 1.905964F, 0.14318F, 6.5F, 5.5F);

		builder.addVertex(0.2825F, 1.6988F, 0.429682F, 5.125F, 5.5F);
		builder.addVertex(0.72F, 1.6988F, 0.429682F, 5.625F, 5.5F);
		builder.addVertex(0.72F, 1.945633F, 0.390013F, 5.625F, 3.5F);
		builder.addVertex(0.2825F, 1.945633F, 0.390013F, 5.125F, 3.5F);

		builder.addVertex(0.2825F, 1.945633F, 0.390013F, 5.125F, 3.5F);
		builder.addVertex(0.72F, 1.945633F, 0.390013F, 5.625F, 3.5F);
		builder.addVertex(0.72F, 1.6988F, 0.429682F, 5.625F, 5.5F);
		builder.addVertex(0.2825F, 1.6988F, 0.429682F, 5.125F, 5.5F);

		builder.addVertex(0.2825F, 1.659131F, 0.182849F, 4.25F, 5.5F);
		builder.addVertex(0.2825F, 1.905964F, 0.14318F, 4.25F, 3.5F);
		builder.addVertex(0.72F, 1.905964F, 0.14318F, 5.125F, 3.5F);
		builder.addVertex(0.72F, 1.659131F, 0.182849F, 5.125F, 5.5F);

		builder.addVertex(0.72F, 1.659131F, 0.182849F, 5.125F, 5.5F);
		builder.addVertex(0.72F, 1.905964F, 0.14318F, 5.125F, 3.5F);
		builder.addVertex(0.2825F, 1.905964F, 0.14318F, 4.25F, 3.5F);
		builder.addVertex(0.2825F, 1.659131F, 0.182849F, 4.25F, 5.5F);

		builder.addVertex(0.72F, 1.659131F, 0.182849F, 5.125F, 5.5F);
		builder.addVertex(0.72F, 1.905964F, 0.14318F, 5.625F, 5.5F);
		builder.addVertex(0.72F, 1.945633F, 0.390013F, 5.625F, 7.5F);
		builder.addVertex(0.72F, 1.6988F, 0.429682F, 5.125F, 7.5F);

		builder.addVertex(0.72F, 1.6988F, 0.429682F, 5.125F, 7.5F);
		builder.addVertex(0.72F, 1.945633F, 0.390013F, 5.625F, 7.5F);
		builder.addVertex(0.72F, 1.905964F, 0.14318F, 5.625F, 5.5F);
		builder.addVertex(0.72F, 1.659131F, 0.182849F, 5.125F, 5.5F);

		builder.addVertex(0.2825F, 1.659131F, 0.182849F, 4.25F, 5.5F);
		builder.addVertex(0.2825F, 1.6988F, 0.429682F, 4.25F, 7.5F);
		builder.addVertex(0.2825F, 1.945633F, 0.390013F, 3.75F, 7.5F);
		builder.addVertex(0.2825F, 1.905964F, 0.14318F, 3.75F, 5.5F);

		builder.addVertex(0.2825F, 1.905964F, 0.14318F, 3.75F, 5.5F);
		builder.addVertex(0.2825F, 1.945633F, 0.390013F, 3.75F, 7.5F);
		builder.addVertex(0.2825F, 1.6988F, 0.429682F, 4.25F, 7.5F);
		builder.addVertex(0.2825F, 1.659131F, 0.182849F, 4.25F, 5.5F);

		//stalk1
		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 1F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 1F);
		builder.addVertex(0.5625F, -0.065281F, 0.440411F, 0.5F, 4.5F);
		builder.addVertex(0.4375F, -0.065281F, 0.440411F, 0.25F, 4.5F);

		builder.addVertex(0.4375F, -0.065281F, 0.440411F, 0.25F, 4.5F);
		builder.addVertex(0.5625F, -0.065281F, 0.440411F, 0.5F, 4.5F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 1F);
		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 1F);

		builder.addVertex(0.4375F, 0.377457F, 0.545359F, 1F, 1F);
		builder.addVertex(0.4375F, -0.059589F, 0.565281F, 1F, 4.5F);
		builder.addVertex(0.5625F, -0.059589F, 0.565281F, 0.75F, 4.5F);
		builder.addVertex(0.5625F, 0.377457F, 0.545359F, 0.75F, 1F);

		builder.addVertex(0.5625F, 0.377457F, 0.545359F, 0.75F, 1F);
		builder.addVertex(0.5625F, -0.059589F, 0.565281F, 0.75F, 4.5F);
		builder.addVertex(0.4375F, -0.059589F, 0.565281F, 1F, 4.5F);
		builder.addVertex(0.4375F, 0.377457F, 0.545359F, 1F, 1F);

		builder.addVertex(0.4375F, -0.065281F, 0.440411F, 0.5F, 1F);
		builder.addVertex(0.5625F, -0.065281F, 0.440411F, 0.75F, 1F);
		builder.addVertex(0.5625F, -0.059589F, 0.565281F, 0.75F, 0F);
		builder.addVertex(0.4375F, -0.059589F, 0.565281F, 0.5F, 0F);

		builder.addVertex(0.4375F, -0.059589F, 0.565281F, 0.5F, 0F);
		builder.addVertex(0.5625F, -0.059589F, 0.565281F, 0.75F, 0F);
		builder.addVertex(0.5625F, -0.065281F, 0.440411F, 0.75F, 1F);
		builder.addVertex(0.4375F, -0.065281F, 0.440411F, 0.5F, 1F);

		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 1F);
		builder.addVertex(0.4375F, 0.377457F, 0.545359F, 0.25F, 0F);
		builder.addVertex(0.5625F, 0.377457F, 0.545359F, 0.5F, 0F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 1F);

		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 1F);
		builder.addVertex(0.5625F, 0.377457F, 0.545359F, 0.5F, 0F);
		builder.addVertex(0.4375F, 0.377457F, 0.545359F, 0.25F, 0F);
		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 1F);

		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 1F);
		builder.addVertex(0.5625F, 0.377457F, 0.545359F, 0.75F, 1F);
		builder.addVertex(0.5625F, -0.059589F, 0.565281F, 0.75F, 4.5F);
		builder.addVertex(0.5625F, -0.065281F, 0.440411F, 0.5F, 4.5F);

		builder.addVertex(0.5625F, -0.065281F, 0.440411F, 0.5F, 4.5F);
		builder.addVertex(0.5625F, -0.059589F, 0.565281F, 0.75F, 4.5F);
		builder.addVertex(0.5625F, 0.377457F, 0.545359F, 0.75F, 1F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 1F);

		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 1F);
		builder.addVertex(0.4375F, -0.065281F, 0.440411F, 0.25F, 4.5F);
		builder.addVertex(0.4375F, -0.059589F, 0.565281F, 0F, 4.5F);
		builder.addVertex(0.4375F, 0.377457F, 0.545359F, 0F, 1F);

		builder.addVertex(0.4375F, 0.377457F, 0.545359F, 0F, 1F);
		builder.addVertex(0.4375F, -0.059589F, 0.565281F, 0F, 4.5F);
		builder.addVertex(0.4375F, -0.065281F, 0.440411F, 0.25F, 4.5F);
		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 1F);

		//stalk4
		builder.addVertex(0.40625F, 1.482577F, 0.473476F, 1.5F, 1.5F);
		builder.addVertex(0.59375F, 1.482577F, 0.473476F, 1.875F, 1.5F);
		builder.addVertex(0.59375F, 1.107966F, 0.456399F, 1.875F, 4.5F);
		builder.addVertex(0.40625F, 1.107966F, 0.456399F, 1.5F, 4.5F);

		builder.addVertex(0.40625F, 1.107966F, 0.456399F, 1.5F, 4.5F);
		builder.addVertex(0.59375F, 1.107966F, 0.456399F, 1.875F, 4.5F);
		builder.addVertex(0.59375F, 1.482577F, 0.473476F, 1.875F, 1.5F);
		builder.addVertex(0.40625F, 1.482577F, 0.473476F, 1.5F, 1.5F);

		builder.addVertex(0.40625F, 1.474038F, 0.660781F, 2.625F, 1.5F);
		builder.addVertex(0.40625F, 1.099427F, 0.643705F, 2.625F, 4.5F);
		builder.addVertex(0.59375F, 1.099427F, 0.643705F, 2.25F, 4.5F);
		builder.addVertex(0.59375F, 1.474038F, 0.660781F, 2.25F, 1.5F);

		builder.addVertex(0.59375F, 1.474038F, 0.660781F, 2.25F, 1.5F);
		builder.addVertex(0.59375F, 1.099427F, 0.643705F, 2.25F, 4.5F);
		builder.addVertex(0.40625F, 1.099427F, 0.643705F, 2.625F, 4.5F);
		builder.addVertex(0.40625F, 1.474038F, 0.660781F, 2.625F, 1.5F);

		builder.addVertex(0.40625F, 1.107966F, 0.456399F, 1.875F, 1.5F);
		builder.addVertex(0.59375F, 1.107966F, 0.456399F, 2.25F, 1.5F);
		builder.addVertex(0.59375F, 1.099427F, 0.643705F, 2.25F, 0F);
		builder.addVertex(0.40625F, 1.099427F, 0.643705F, 1.875F, 0F);

		builder.addVertex(0.40625F, 1.099427F, 0.643705F, 1.875F, 0F);
		builder.addVertex(0.59375F, 1.099427F, 0.643705F, 2.25F, 0F);
		builder.addVertex(0.59375F, 1.107966F, 0.456399F, 2.25F, 1.5F);
		builder.addVertex(0.40625F, 1.107966F, 0.456399F, 1.875F, 1.5F);

		builder.addVertex(0.40625F, 1.482577F, 0.473476F, 1.5F, 1.5F);
		builder.addVertex(0.40625F, 1.474038F, 0.660781F, 1.5F, 0F);
		builder.addVertex(0.59375F, 1.474038F, 0.660781F, 1.875F, 0F);
		builder.addVertex(0.59375F, 1.482577F, 0.473476F, 1.875F, 1.5F);

		builder.addVertex(0.59375F, 1.482577F, 0.473476F, 1.875F, 1.5F);
		builder.addVertex(0.59375F, 1.474038F, 0.660781F, 1.875F, 0F);
		builder.addVertex(0.40625F, 1.474038F, 0.660781F, 1.5F, 0F);
		builder.addVertex(0.40625F, 1.482577F, 0.473476F, 1.5F, 1.5F);

		builder.addVertex(0.59375F, 1.482577F, 0.473476F, 1.875F, 1.5F);
		builder.addVertex(0.59375F, 1.474038F, 0.660781F, 2.25F, 1.5F);
		builder.addVertex(0.59375F, 1.099427F, 0.643705F, 2.25F, 4.5F);
		builder.addVertex(0.59375F, 1.107966F, 0.456399F, 1.875F, 4.5F);

		builder.addVertex(0.59375F, 1.107966F, 0.456399F, 1.875F, 4.5F);
		builder.addVertex(0.59375F, 1.099427F, 0.643705F, 2.25F, 4.5F);
		builder.addVertex(0.59375F, 1.474038F, 0.660781F, 2.25F, 1.5F);
		builder.addVertex(0.59375F, 1.482577F, 0.473476F, 1.875F, 1.5F);

		builder.addVertex(0.40625F, 1.482577F, 0.473476F, 1.5F, 1.5F);
		builder.addVertex(0.40625F, 1.107966F, 0.456399F, 1.5F, 4.5F);
		builder.addVertex(0.40625F, 1.099427F, 0.643705F, 1.125F, 4.5F);
		builder.addVertex(0.40625F, 1.474038F, 0.660781F, 1.125F, 1.5F);

		builder.addVertex(0.40625F, 1.474038F, 0.660781F, 1.125F, 1.5F);
		builder.addVertex(0.40625F, 1.099427F, 0.643705F, 1.125F, 4.5F);
		builder.addVertex(0.40625F, 1.107966F, 0.456399F, 1.5F, 4.5F);
		builder.addVertex(0.40625F, 1.482577F, 0.473476F, 1.5F, 1.5F);

		//flowerthing4
		builder.addVertex(0.31375F, 1.694944F, 0.208744F, 4.125F, 1.5F);
		builder.addVertex(0.68875F, 1.694944F, 0.208744F, 4.875F, 1.5F);
		builder.addVertex(0.68875F, 1.724696F, 0.393869F, 4.875F, 3F);
		builder.addVertex(0.31375F, 1.724696F, 0.393869F, 4.125F, 3F);

		builder.addVertex(0.31375F, 1.724696F, 0.393869F, 4.125F, 3F);
		builder.addVertex(0.68875F, 1.724696F, 0.393869F, 4.875F, 3F);
		builder.addVertex(0.68875F, 1.694944F, 0.208744F, 4.875F, 1.5F);
		builder.addVertex(0.31375F, 1.694944F, 0.208744F, 4.125F, 1.5F);

		builder.addVertex(0.31375F, 1.880069F, 0.178993F, 6F, 1.5F);
		builder.addVertex(0.31375F, 1.90982F, 0.364117F, 6F, 3F);
		builder.addVertex(0.68875F, 1.90982F, 0.364117F, 5.25F, 3F);
		builder.addVertex(0.68875F, 1.880069F, 0.178993F, 5.25F, 1.5F);

		builder.addVertex(0.68875F, 1.880069F, 0.178993F, 5.25F, 1.5F);
		builder.addVertex(0.68875F, 1.90982F, 0.364117F, 5.25F, 3F);
		builder.addVertex(0.31375F, 1.90982F, 0.364117F, 6F, 3F);
		builder.addVertex(0.31375F, 1.880069F, 0.178993F, 6F, 1.5F);

		builder.addVertex(0.31375F, 1.724696F, 0.393869F, 4.875F, 1.5F);
		builder.addVertex(0.68875F, 1.724696F, 0.393869F, 5.25F, 1.5F);
		builder.addVertex(0.68875F, 1.90982F, 0.364117F, 5.25F, 0F);
		builder.addVertex(0.31375F, 1.90982F, 0.364117F, 4.875F, 0F);

		builder.addVertex(0.31375F, 1.90982F, 0.364117F, 4.875F, 0F);
		builder.addVertex(0.68875F, 1.90982F, 0.364117F, 5.25F, 0F);
		builder.addVertex(0.68875F, 1.724696F, 0.393869F, 5.25F, 1.5F);
		builder.addVertex(0.31375F, 1.724696F, 0.393869F, 4.875F, 1.5F);

		builder.addVertex(0.31375F, 1.694944F, 0.208744F, 4.125F, 1.5F);
		builder.addVertex(0.31375F, 1.880069F, 0.178993F, 4.125F, 0F);
		builder.addVertex(0.68875F, 1.880069F, 0.178993F, 4.875F, 0F);
		builder.addVertex(0.68875F, 1.694944F, 0.208744F, 4.875F, 1.5F);

		builder.addVertex(0.68875F, 1.694944F, 0.208744F, 4.875F, 1.5F);
		builder.addVertex(0.68875F, 1.880069F, 0.178993F, 4.875F, 0F);
		builder.addVertex(0.31375F, 1.880069F, 0.178993F, 4.125F, 0F);
		builder.addVertex(0.31375F, 1.694944F, 0.208744F, 4.125F, 1.5F);

		builder.addVertex(0.68875F, 1.694944F, 0.208744F, 4.875F, 1.5F);
		builder.addVertex(0.68875F, 1.880069F, 0.178993F, 5.25F, 1.5F);
		builder.addVertex(0.68875F, 1.90982F, 0.364117F, 5.25F, 3F);
		builder.addVertex(0.68875F, 1.724696F, 0.393869F, 4.875F, 3F);

		builder.addVertex(0.68875F, 1.724696F, 0.393869F, 4.875F, 3F);
		builder.addVertex(0.68875F, 1.90982F, 0.364117F, 5.25F, 3F);
		builder.addVertex(0.68875F, 1.880069F, 0.178993F, 5.25F, 1.5F);
		builder.addVertex(0.68875F, 1.694944F, 0.208744F, 4.875F, 1.5F);

		builder.addVertex(0.31375F, 1.694944F, 0.208744F, 4.125F, 1.5F);
		builder.addVertex(0.31375F, 1.724696F, 0.393869F, 4.125F, 3F);
		builder.addVertex(0.31375F, 1.90982F, 0.364117F, 3.75F, 3F);
		builder.addVertex(0.31375F, 1.880069F, 0.178993F, 3.75F, 1.5F);

		builder.addVertex(0.31375F, 1.880069F, 0.178993F, 3.75F, 1.5F);
		builder.addVertex(0.31375F, 1.90982F, 0.364117F, 3.75F, 3F);
		builder.addVertex(0.31375F, 1.724696F, 0.393869F, 4.125F, 3F);
		builder.addVertex(0.31375F, 1.694944F, 0.208744F, 4.125F, 1.5F);

		//hairs1
		builder.addVertex(0.28125F, 1.659285F, 0.412674F, 7.25F, 7F);
		builder.addVertex(0.71875F, 1.659285F, 0.412674F, 8.125F, 7F);
		builder.addVertex(0.71875F, 1.41161F, 0.446689F, 8.125F, 9F);
		builder.addVertex(0.28125F, 1.41161F, 0.446689F, 7.25F, 9F);

		builder.addVertex(0.28125F, 1.41161F, 0.446689F, 7.25F, 9F);
		builder.addVertex(0.71875F, 1.41161F, 0.446689F, 8.125F, 9F);
		builder.addVertex(0.71875F, 1.659285F, 0.412674F, 8.125F, 7F);
		builder.addVertex(0.28125F, 1.659285F, 0.412674F, 7.25F, 7F);

		builder.addVertex(0.28125F, 1.6933F, 0.660349F, 9.5F, 7F);
		builder.addVertex(0.28125F, 1.445625F, 0.694364F, 9.5F, 9F);
		builder.addVertex(0.71875F, 1.445625F, 0.694364F, 8.625F, 9F);
		builder.addVertex(0.71875F, 1.6933F, 0.660349F, 8.625F, 7F);

		builder.addVertex(0.71875F, 1.6933F, 0.660349F, 8.625F, 7F);
		builder.addVertex(0.71875F, 1.445625F, 0.694364F, 8.625F, 9F);
		builder.addVertex(0.28125F, 1.445625F, 0.694364F, 9.5F, 9F);
		builder.addVertex(0.28125F, 1.6933F, 0.660349F, 9.5F, 7F);

		builder.addVertex(0.28125F, 1.41161F, 0.446689F, 8.125F, 7F);
		builder.addVertex(0.71875F, 1.41161F, 0.446689F, 8.625F, 7F);
		builder.addVertex(0.71875F, 1.445625F, 0.694364F, 8.625F, 5F);
		builder.addVertex(0.28125F, 1.445625F, 0.694364F, 8.125F, 5F);

		builder.addVertex(0.28125F, 1.445625F, 0.694364F, 8.125F, 5F);
		builder.addVertex(0.71875F, 1.445625F, 0.694364F, 8.625F, 5F);
		builder.addVertex(0.71875F, 1.41161F, 0.446689F, 8.625F, 7F);
		builder.addVertex(0.28125F, 1.41161F, 0.446689F, 8.125F, 7F);

		builder.addVertex(0.28125F, 1.659285F, 0.412674F, 7.25F, 7F);
		builder.addVertex(0.28125F, 1.6933F, 0.660349F, 7.25F, 5F);
		builder.addVertex(0.71875F, 1.6933F, 0.660349F, 8.125F, 5F);
		builder.addVertex(0.71875F, 1.659285F, 0.412674F, 8.125F, 7F);

		builder.addVertex(0.71875F, 1.659285F, 0.412674F, 8.125F, 7F);
		builder.addVertex(0.71875F, 1.6933F, 0.660349F, 8.125F, 5F);
		builder.addVertex(0.28125F, 1.6933F, 0.660349F, 7.25F, 5F);
		builder.addVertex(0.28125F, 1.659285F, 0.412674F, 7.25F, 7F);

		builder.addVertex(0.71875F, 1.659285F, 0.412674F, 8.125F, 7F);
		builder.addVertex(0.71875F, 1.6933F, 0.660349F, 8.625F, 7F);
		builder.addVertex(0.71875F, 1.445625F, 0.694364F, 8.625F, 9F);
		builder.addVertex(0.71875F, 1.41161F, 0.446689F, 8.125F, 9F);

		builder.addVertex(0.71875F, 1.41161F, 0.446689F, 8.125F, 9F);
		builder.addVertex(0.71875F, 1.445625F, 0.694364F, 8.625F, 9F);
		builder.addVertex(0.71875F, 1.6933F, 0.660349F, 8.625F, 7F);
		builder.addVertex(0.71875F, 1.659285F, 0.412674F, 8.125F, 7F);

		builder.addVertex(0.28125F, 1.659285F, 0.412674F, 7.25F, 7F);
		builder.addVertex(0.28125F, 1.41161F, 0.446689F, 7.25F, 9F);
		builder.addVertex(0.28125F, 1.445625F, 0.694364F, 6.75F, 9F);
		builder.addVertex(0.28125F, 1.6933F, 0.660349F, 6.75F, 7F);

		builder.addVertex(0.28125F, 1.6933F, 0.660349F, 6.75F, 7F);
		builder.addVertex(0.28125F, 1.445625F, 0.694364F, 6.75F, 9F);
		builder.addVertex(0.28125F, 1.41161F, 0.446689F, 7.25F, 9F);
		builder.addVertex(0.28125F, 1.659285F, 0.412674F, 7.25F, 7F);

		//hairs2
		builder.addVertex(0.25F, 1.666514F, 0.277436F, 6.75F, 2.5F);
		builder.addVertex(0.75F, 1.666514F, 0.277436F, 7.75F, 2.5F);
		builder.addVertex(0.75F, 1.465602F, 0.426212F, 7.75F, 4.5F);
		builder.addVertex(0.25F, 1.465602F, 0.426212F, 6.75F, 4.5F);

		builder.addVertex(0.25F, 1.465602F, 0.426212F, 6.75F, 4.5F);
		builder.addVertex(0.75F, 1.465602F, 0.426212F, 7.75F, 4.5F);
		builder.addVertex(0.75F, 1.666514F, 0.277436F, 7.75F, 2.5F);
		builder.addVertex(0.25F, 1.666514F, 0.277436F, 6.75F, 2.5F);

		builder.addVertex(0.25F, 1.852484F, 0.528577F, 9.375F, 2.5F);
		builder.addVertex(0.25F, 1.651572F, 0.677352F, 9.375F, 4.5F);
		builder.addVertex(0.75F, 1.651572F, 0.677352F, 8.375F, 4.5F);
		builder.addVertex(0.75F, 1.852484F, 0.528577F, 8.375F, 2.5F);

		builder.addVertex(0.75F, 1.852484F, 0.528577F, 8.375F, 2.5F);
		builder.addVertex(0.75F, 1.651572F, 0.677352F, 8.375F, 4.5F);
		builder.addVertex(0.25F, 1.651572F, 0.677352F, 9.375F, 4.5F);
		builder.addVertex(0.25F, 1.852484F, 0.528577F, 9.375F, 2.5F);

		builder.addVertex(0.25F, 1.465602F, 0.426212F, 7.75F, 2.5F);
		builder.addVertex(0.75F, 1.465602F, 0.426212F, 8.375F, 2.5F);
		builder.addVertex(0.75F, 1.651572F, 0.677352F, 8.375F, 0F);
		builder.addVertex(0.25F, 1.651572F, 0.677352F, 7.75F, 0F);

		builder.addVertex(0.25F, 1.651572F, 0.677352F, 7.75F, 0F);
		builder.addVertex(0.75F, 1.651572F, 0.677352F, 8.375F, 0F);
		builder.addVertex(0.75F, 1.465602F, 0.426212F, 8.375F, 2.5F);
		builder.addVertex(0.25F, 1.465602F, 0.426212F, 7.75F, 2.5F);

		builder.addVertex(0.25F, 1.666514F, 0.277436F, 6.75F, 2.5F);
		builder.addVertex(0.25F, 1.852484F, 0.528577F, 6.75F, 0F);
		builder.addVertex(0.75F, 1.852484F, 0.528577F, 7.75F, 0F);
		builder.addVertex(0.75F, 1.666514F, 0.277436F, 7.75F, 2.5F);

		builder.addVertex(0.75F, 1.666514F, 0.277436F, 7.75F, 2.5F);
		builder.addVertex(0.75F, 1.852484F, 0.528577F, 7.75F, 0F);
		builder.addVertex(0.25F, 1.852484F, 0.528577F, 6.75F, 0F);
		builder.addVertex(0.25F, 1.666514F, 0.277436F, 6.75F, 2.5F);

		builder.addVertex(0.75F, 1.666514F, 0.277436F, 7.75F, 2.5F);
		builder.addVertex(0.75F, 1.852484F, 0.528577F, 8.375F, 2.5F);
		builder.addVertex(0.75F, 1.651572F, 0.677352F, 8.375F, 4.5F);
		builder.addVertex(0.75F, 1.465602F, 0.426212F, 7.75F, 4.5F);

		builder.addVertex(0.75F, 1.465602F, 0.426212F, 7.75F, 4.5F);
		builder.addVertex(0.75F, 1.651572F, 0.677352F, 8.375F, 4.5F);
		builder.addVertex(0.75F, 1.852484F, 0.528577F, 8.375F, 2.5F);
		builder.addVertex(0.75F, 1.666514F, 0.277436F, 7.75F, 2.5F);

		builder.addVertex(0.25F, 1.666514F, 0.277436F, 6.75F, 2.5F);
		builder.addVertex(0.25F, 1.465602F, 0.426212F, 6.75F, 4.5F);
		builder.addVertex(0.25F, 1.651572F, 0.677352F, 6.125F, 4.5F);
		builder.addVertex(0.25F, 1.852484F, 0.528577F, 6.125F, 2.5F);

		builder.addVertex(0.25F, 1.852484F, 0.528577F, 6.125F, 2.5F);
		builder.addVertex(0.25F, 1.651572F, 0.677352F, 6.125F, 4.5F);
		builder.addVertex(0.25F, 1.465602F, 0.426212F, 6.75F, 4.5F);
		builder.addVertex(0.25F, 1.666514F, 0.277436F, 6.75F, 2.5F);

		//flowerthing3
		builder.addVertex(0.281875F, 1.699231F, 0.229388F, 1.625F, 14.5F);
		builder.addVertex(0.719375F, 1.699231F, 0.229388F, 2.5F, 14.5F);
		builder.addVertex(0.719375F, 1.598184F, 0.38733F, 2.5F, 16F);
		builder.addVertex(0.281875F, 1.598184F, 0.38733F, 1.625F, 16F);

		builder.addVertex(0.281875F, 1.598184F, 0.38733F, 1.625F, 16F);
		builder.addVertex(0.719375F, 1.598184F, 0.38733F, 2.5F, 16F);
		builder.addVertex(0.719375F, 1.699231F, 0.229388F, 2.5F, 14.5F);
		builder.addVertex(0.281875F, 1.699231F, 0.229388F, 1.625F, 14.5F);

		builder.addVertex(0.281875F, 1.90982F, 0.364117F, 3.875F, 14.5F);
		builder.addVertex(0.281875F, 1.808773F, 0.52206F, 3.875F, 16F);
		builder.addVertex(0.719375F, 1.808773F, 0.52206F, 3F, 16F);
		builder.addVertex(0.719375F, 1.90982F, 0.364117F, 3F, 14.5F);

		builder.addVertex(0.719375F, 1.90982F, 0.364117F, 3F, 14.5F);
		builder.addVertex(0.719375F, 1.808773F, 0.52206F, 3F, 16F);
		builder.addVertex(0.281875F, 1.808773F, 0.52206F, 3.875F, 16F);
		builder.addVertex(0.281875F, 1.90982F, 0.364117F, 3.875F, 14.5F);

		builder.addVertex(0.281875F, 1.598184F, 0.38733F, 2.5F, 14.5F);
		builder.addVertex(0.719375F, 1.598184F, 0.38733F, 3F, 14.5F);
		builder.addVertex(0.719375F, 1.808773F, 0.52206F, 3F, 12.5F);
		builder.addVertex(0.281875F, 1.808773F, 0.52206F, 2.5F, 12.5F);

		builder.addVertex(0.281875F, 1.808773F, 0.52206F, 2.5F, 12.5F);
		builder.addVertex(0.719375F, 1.808773F, 0.52206F, 3F, 12.5F);
		builder.addVertex(0.719375F, 1.598184F, 0.38733F, 3F, 14.5F);
		builder.addVertex(0.281875F, 1.598184F, 0.38733F, 2.5F, 14.5F);

		builder.addVertex(0.281875F, 1.699231F, 0.229388F, 1.625F, 14.5F);
		builder.addVertex(0.281875F, 1.90982F, 0.364117F, 1.625F, 12.5F);
		builder.addVertex(0.719375F, 1.90982F, 0.364117F, 2.5F, 12.5F);
		builder.addVertex(0.719375F, 1.699231F, 0.229388F, 2.5F, 14.5F);

		builder.addVertex(0.719375F, 1.699231F, 0.229388F, 2.5F, 14.5F);
		builder.addVertex(0.719375F, 1.90982F, 0.364117F, 2.5F, 12.5F);
		builder.addVertex(0.281875F, 1.90982F, 0.364117F, 1.625F, 12.5F);
		builder.addVertex(0.281875F, 1.699231F, 0.229388F, 1.625F, 14.5F);

		builder.addVertex(0.719375F, 1.699231F, 0.229388F, 2.5F, 14.5F);
		builder.addVertex(0.719375F, 1.90982F, 0.364117F, 3F, 14.5F);
		builder.addVertex(0.719375F, 1.808773F, 0.52206F, 3F, 16F);
		builder.addVertex(0.719375F, 1.598184F, 0.38733F, 2.5F, 16F);

		builder.addVertex(0.719375F, 1.598184F, 0.38733F, 2.5F, 16F);
		builder.addVertex(0.719375F, 1.808773F, 0.52206F, 3F, 16F);
		builder.addVertex(0.719375F, 1.90982F, 0.364117F, 3F, 14.5F);
		builder.addVertex(0.719375F, 1.699231F, 0.229388F, 2.5F, 14.5F);

		builder.addVertex(0.281875F, 1.699231F, 0.229388F, 1.625F, 14.5F);
		builder.addVertex(0.281875F, 1.598184F, 0.38733F, 1.625F, 16F);
		builder.addVertex(0.281875F, 1.808773F, 0.52206F, 1.125F, 16F);
		builder.addVertex(0.281875F, 1.90982F, 0.364117F, 1.125F, 14.5F);

		builder.addVertex(0.281875F, 1.90982F, 0.364117F, 1.125F, 14.5F);
		builder.addVertex(0.281875F, 1.808773F, 0.52206F, 1.125F, 16F);
		builder.addVertex(0.281875F, 1.598184F, 0.38733F, 1.625F, 16F);
		builder.addVertex(0.281875F, 1.699231F, 0.229388F, 1.625F, 14.5F);

		//stalk3
		builder.addVertex(0.4375F, 1.11788F, 0.488653F, 0.25F, 10.5F);
		builder.addVertex(0.5625F, 1.11788F, 0.488653F, 0.5F, 10.5F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 13.5F);
		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 13.5F);

		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 13.5F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 13.5F);
		builder.addVertex(0.5625F, 1.11788F, 0.488653F, 0.5F, 10.5F);
		builder.addVertex(0.4375F, 1.11788F, 0.488653F, 0.25F, 10.5F);

		builder.addVertex(0.4375F, 1.10085F, 0.612487F, 1F, 10.5F);
		builder.addVertex(0.4375F, 0.729347F, 0.561399F, 1F, 13.5F);
		builder.addVertex(0.5625F, 0.729347F, 0.561399F, 0.75F, 13.5F);
		builder.addVertex(0.5625F, 1.10085F, 0.612487F, 0.75F, 10.5F);

		builder.addVertex(0.5625F, 1.10085F, 0.612487F, 0.75F, 10.5F);
		builder.addVertex(0.5625F, 0.729347F, 0.561399F, 0.75F, 13.5F);
		builder.addVertex(0.4375F, 0.729347F, 0.561399F, 1F, 13.5F);
		builder.addVertex(0.4375F, 1.10085F, 0.612487F, 1F, 10.5F);

		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.5F, 10.5F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.75F, 10.5F);
		builder.addVertex(0.5625F, 0.729347F, 0.561399F, 0.75F, 9.5F);
		builder.addVertex(0.4375F, 0.729347F, 0.561399F, 0.5F, 9.5F);

		builder.addVertex(0.4375F, 0.729347F, 0.561399F, 0.5F, 9.5F);
		builder.addVertex(0.5625F, 0.729347F, 0.561399F, 0.75F, 9.5F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.75F, 10.5F);
		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.5F, 10.5F);

		builder.addVertex(0.4375F, 1.11788F, 0.488653F, 0.25F, 10.5F);
		builder.addVertex(0.4375F, 1.10085F, 0.612487F, 0.25F, 9.5F);
		builder.addVertex(0.5625F, 1.10085F, 0.612487F, 0.5F, 9.5F);
		builder.addVertex(0.5625F, 1.11788F, 0.488653F, 0.5F, 10.5F);

		builder.addVertex(0.5625F, 1.11788F, 0.488653F, 0.5F, 10.5F);
		builder.addVertex(0.5625F, 1.10085F, 0.612487F, 0.5F, 9.5F);
		builder.addVertex(0.4375F, 1.10085F, 0.612487F, 0.25F, 9.5F);
		builder.addVertex(0.4375F, 1.11788F, 0.488653F, 0.25F, 10.5F);

		builder.addVertex(0.5625F, 1.11788F, 0.488653F, 0.5F, 10.5F);
		builder.addVertex(0.5625F, 1.10085F, 0.612487F, 0.75F, 10.5F);
		builder.addVertex(0.5625F, 0.729347F, 0.561399F, 0.75F, 13.5F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 13.5F);

		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 13.5F);
		builder.addVertex(0.5625F, 0.729347F, 0.561399F, 0.75F, 13.5F);
		builder.addVertex(0.5625F, 1.10085F, 0.612487F, 0.75F, 10.5F);
		builder.addVertex(0.5625F, 1.11788F, 0.488653F, 0.5F, 10.5F);

		builder.addVertex(0.4375F, 1.11788F, 0.488653F, 0.25F, 10.5F);
		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 13.5F);
		builder.addVertex(0.4375F, 0.729347F, 0.561399F, 0F, 13.5F);
		builder.addVertex(0.4375F, 1.10085F, 0.612487F, 0F, 10.5F);

		builder.addVertex(0.4375F, 1.10085F, 0.612487F, 0F, 10.5F);
		builder.addVertex(0.4375F, 0.729347F, 0.561399F, 0F, 13.5F);
		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 13.5F);
		builder.addVertex(0.4375F, 1.11788F, 0.488653F, 0.25F, 10.5F);

		//flowerthing1
		builder.addVertex(0.3125F, 1.632577F, 0.447885F, 1.5F, 6.5F);
		builder.addVertex(0.6875F, 1.632577F, 0.447885F, 2.25F, 6.5F);
		builder.addVertex(0.6875F, 1.446821F, 0.473397F, 2.25F, 8F);
		builder.addVertex(0.3125F, 1.446821F, 0.473397F, 1.5F, 8F);

		builder.addVertex(0.3125F, 1.446821F, 0.473397F, 1.5F, 8F);
		builder.addVertex(0.6875F, 1.446821F, 0.473397F, 2.25F, 8F);
		builder.addVertex(0.6875F, 1.632577F, 0.447885F, 2.25F, 6.5F);
		builder.addVertex(0.3125F, 1.632577F, 0.447885F, 1.5F, 6.5F);

		builder.addVertex(0.3125F, 1.658089F, 0.633641F, 3.375F, 6.5F);
		builder.addVertex(0.3125F, 1.472333F, 0.659153F, 3.375F, 8F);
		builder.addVertex(0.6875F, 1.472333F, 0.659153F, 2.625F, 8F);
		builder.addVertex(0.6875F, 1.658089F, 0.633641F, 2.625F, 6.5F);

		builder.addVertex(0.6875F, 1.658089F, 0.633641F, 2.625F, 6.5F);
		builder.addVertex(0.6875F, 1.472333F, 0.659153F, 2.625F, 8F);
		builder.addVertex(0.3125F, 1.472333F, 0.659153F, 3.375F, 8F);
		builder.addVertex(0.3125F, 1.658089F, 0.633641F, 3.375F, 6.5F);

		builder.addVertex(0.3125F, 1.446821F, 0.473397F, 2.25F, 6.5F);
		builder.addVertex(0.6875F, 1.446821F, 0.473397F, 2.625F, 6.5F);
		builder.addVertex(0.6875F, 1.472333F, 0.659153F, 2.625F, 5F);
		builder.addVertex(0.3125F, 1.472333F, 0.659153F, 2.25F, 5F);

		builder.addVertex(0.3125F, 1.472333F, 0.659153F, 2.25F, 5F);
		builder.addVertex(0.6875F, 1.472333F, 0.659153F, 2.625F, 5F);
		builder.addVertex(0.6875F, 1.446821F, 0.473397F, 2.625F, 6.5F);
		builder.addVertex(0.3125F, 1.446821F, 0.473397F, 2.25F, 6.5F);

		builder.addVertex(0.3125F, 1.632577F, 0.447885F, 1.5F, 6.5F);
		builder.addVertex(0.3125F, 1.658089F, 0.633641F, 1.5F, 5F);
		builder.addVertex(0.6875F, 1.658089F, 0.633641F, 2.25F, 5F);
		builder.addVertex(0.6875F, 1.632577F, 0.447885F, 2.25F, 6.5F);

		builder.addVertex(0.6875F, 1.632577F, 0.447885F, 2.25F, 6.5F);
		builder.addVertex(0.6875F, 1.658089F, 0.633641F, 2.25F, 5F);
		builder.addVertex(0.3125F, 1.658089F, 0.633641F, 1.5F, 5F);
		builder.addVertex(0.3125F, 1.632577F, 0.447885F, 1.5F, 6.5F);

		builder.addVertex(0.6875F, 1.632577F, 0.447885F, 2.25F, 6.5F);
		builder.addVertex(0.6875F, 1.658089F, 0.633641F, 2.625F, 6.5F);
		builder.addVertex(0.6875F, 1.472333F, 0.659153F, 2.625F, 8F);
		builder.addVertex(0.6875F, 1.446821F, 0.473397F, 2.25F, 8F);

		builder.addVertex(0.6875F, 1.446821F, 0.473397F, 2.25F, 8F);
		builder.addVertex(0.6875F, 1.472333F, 0.659153F, 2.625F, 8F);
		builder.addVertex(0.6875F, 1.658089F, 0.633641F, 2.625F, 6.5F);
		builder.addVertex(0.6875F, 1.632577F, 0.447885F, 2.25F, 6.5F);

		builder.addVertex(0.3125F, 1.632577F, 0.447885F, 1.5F, 6.5F);
		builder.addVertex(0.3125F, 1.446821F, 0.473397F, 1.5F, 8F);
		builder.addVertex(0.3125F, 1.472333F, 0.659153F, 1.125F, 8F);
		builder.addVertex(0.3125F, 1.658089F, 0.633641F, 1.125F, 6.5F);

		builder.addVertex(0.3125F, 1.658089F, 0.633641F, 1.125F, 6.5F);
		builder.addVertex(0.3125F, 1.472333F, 0.659153F, 1.125F, 8F);
		builder.addVertex(0.3125F, 1.446821F, 0.473397F, 1.5F, 8F);
		builder.addVertex(0.3125F, 1.632577F, 0.447885F, 1.5F, 6.5F);

		//flowerthing2
		builder.addVertex(0.28125F, 1.659997F, 0.321147F, 1.625F, 10.5F);
		builder.addVertex(0.71875F, 1.659997F, 0.321147F, 2.5F, 10.5F);
		builder.addVertex(0.71875F, 1.509313F, 0.432729F, 2.5F, 12F);
		builder.addVertex(0.28125F, 1.509313F, 0.432729F, 1.625F, 12F);

		builder.addVertex(0.28125F, 1.509313F, 0.432729F, 1.625F, 12F);
		builder.addVertex(0.71875F, 1.509313F, 0.432729F, 2.5F, 12F);
		builder.addVertex(0.71875F, 1.659997F, 0.321147F, 2.5F, 10.5F);
		builder.addVertex(0.28125F, 1.659997F, 0.321147F, 1.625F, 10.5F);

		builder.addVertex(0.28125F, 1.808773F, 0.52206F, 3.875F, 10.5F);
		builder.addVertex(0.28125F, 1.658089F, 0.633641F, 3.875F, 12F);
		builder.addVertex(0.71875F, 1.658089F, 0.633641F, 3F, 12F);
		builder.addVertex(0.71875F, 1.808773F, 0.52206F, 3F, 10.5F);

		builder.addVertex(0.71875F, 1.808773F, 0.52206F, 3F, 10.5F);
		builder.addVertex(0.71875F, 1.658089F, 0.633641F, 3F, 12F);
		builder.addVertex(0.28125F, 1.658089F, 0.633641F, 3.875F, 12F);
		builder.addVertex(0.28125F, 1.808773F, 0.52206F, 3.875F, 10.5F);

		builder.addVertex(0.28125F, 1.509313F, 0.432729F, 2.5F, 10.5F);
		builder.addVertex(0.71875F, 1.509313F, 0.432729F, 3F, 10.5F);
		builder.addVertex(0.71875F, 1.658089F, 0.633641F, 3F, 8.5F);
		builder.addVertex(0.28125F, 1.658089F, 0.633641F, 2.5F, 8.5F);

		builder.addVertex(0.28125F, 1.658089F, 0.633641F, 2.5F, 8.5F);
		builder.addVertex(0.71875F, 1.658089F, 0.633641F, 3F, 8.5F);
		builder.addVertex(0.71875F, 1.509313F, 0.432729F, 3F, 10.5F);
		builder.addVertex(0.28125F, 1.509313F, 0.432729F, 2.5F, 10.5F);

		builder.addVertex(0.28125F, 1.659997F, 0.321147F, 1.625F, 10.5F);
		builder.addVertex(0.28125F, 1.808773F, 0.52206F, 1.625F, 8.5F);
		builder.addVertex(0.71875F, 1.808773F, 0.52206F, 2.5F, 8.5F);
		builder.addVertex(0.71875F, 1.659997F, 0.321147F, 2.5F, 10.5F);

		builder.addVertex(0.71875F, 1.659997F, 0.321147F, 2.5F, 10.5F);
		builder.addVertex(0.71875F, 1.808773F, 0.52206F, 2.5F, 8.5F);
		builder.addVertex(0.28125F, 1.808773F, 0.52206F, 1.625F, 8.5F);
		builder.addVertex(0.28125F, 1.659997F, 0.321147F, 1.625F, 10.5F);

		builder.addVertex(0.71875F, 1.659997F, 0.321147F, 2.5F, 10.5F);
		builder.addVertex(0.71875F, 1.808773F, 0.52206F, 3F, 10.5F);
		builder.addVertex(0.71875F, 1.658089F, 0.633641F, 3F, 12F);
		builder.addVertex(0.71875F, 1.509313F, 0.432729F, 2.5F, 12F);

		builder.addVertex(0.71875F, 1.509313F, 0.432729F, 2.5F, 12F);
		builder.addVertex(0.71875F, 1.658089F, 0.633641F, 3F, 12F);
		builder.addVertex(0.71875F, 1.808773F, 0.52206F, 3F, 10.5F);
		builder.addVertex(0.71875F, 1.659997F, 0.321147F, 2.5F, 10.5F);

		builder.addVertex(0.28125F, 1.659997F, 0.321147F, 1.625F, 10.5F);
		builder.addVertex(0.28125F, 1.509313F, 0.432729F, 1.625F, 12F);
		builder.addVertex(0.28125F, 1.658089F, 0.633641F, 1.125F, 12F);
		builder.addVertex(0.28125F, 1.808773F, 0.52206F, 1.125F, 10.5F);

		builder.addVertex(0.28125F, 1.808773F, 0.52206F, 1.125F, 10.5F);
		builder.addVertex(0.28125F, 1.658089F, 0.633641F, 1.125F, 12F);
		builder.addVertex(0.28125F, 1.509313F, 0.432729F, 1.625F, 12F);
		builder.addVertex(0.28125F, 1.659997F, 0.321147F, 1.625F, 10.5F);

		//stalk2
		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 6F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 6F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 9F);
		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 9F);

		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 9F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 9F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 6F);
		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 6F);

		builder.addVertex(0.4375F, 0.740684F, 0.562435F, 1F, 6F);
		builder.addVertex(0.4375F, 0.366073F, 0.545359F, 1F, 9F);
		builder.addVertex(0.5625F, 0.366073F, 0.545359F, 0.75F, 9F);
		builder.addVertex(0.5625F, 0.740684F, 0.562435F, 0.75F, 6F);

		builder.addVertex(0.5625F, 0.740684F, 0.562435F, 0.75F, 6F);
		builder.addVertex(0.5625F, 0.366073F, 0.545359F, 0.75F, 9F);
		builder.addVertex(0.4375F, 0.366073F, 0.545359F, 1F, 9F);
		builder.addVertex(0.4375F, 0.740684F, 0.562435F, 1F, 6F);

		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.5F, 6F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.75F, 6F);
		builder.addVertex(0.5625F, 0.366073F, 0.545359F, 0.75F, 5F);
		builder.addVertex(0.4375F, 0.366073F, 0.545359F, 0.5F, 5F);

		builder.addVertex(0.4375F, 0.366073F, 0.545359F, 0.5F, 5F);
		builder.addVertex(0.5625F, 0.366073F, 0.545359F, 0.75F, 5F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.75F, 6F);
		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.5F, 6F);

		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 6F);
		builder.addVertex(0.4375F, 0.740684F, 0.562435F, 0.25F, 5F);
		builder.addVertex(0.5625F, 0.740684F, 0.562435F, 0.5F, 5F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 6F);

		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 6F);
		builder.addVertex(0.5625F, 0.740684F, 0.562435F, 0.5F, 5F);
		builder.addVertex(0.4375F, 0.740684F, 0.562435F, 0.25F, 5F);
		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 6F);

		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 6F);
		builder.addVertex(0.5625F, 0.740684F, 0.562435F, 0.75F, 6F);
		builder.addVertex(0.5625F, 0.366073F, 0.545359F, 0.75F, 9F);
		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 9F);

		builder.addVertex(0.5625F, 0.371765F, 0.420488F, 0.5F, 9F);
		builder.addVertex(0.5625F, 0.366073F, 0.545359F, 0.75F, 9F);
		builder.addVertex(0.5625F, 0.740684F, 0.562435F, 0.75F, 6F);
		builder.addVertex(0.5625F, 0.746376F, 0.437565F, 0.5F, 6F);

		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 6F);
		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 9F);
		builder.addVertex(0.4375F, 0.366073F, 0.545359F, 0F, 9F);
		builder.addVertex(0.4375F, 0.740684F, 0.562435F, 0F, 6F);

		builder.addVertex(0.4375F, 0.740684F, 0.562435F, 0F, 6F);
		builder.addVertex(0.4375F, 0.366073F, 0.545359F, 0F, 9F);
		builder.addVertex(0.4375F, 0.371765F, 0.420488F, 0.25F, 9F);
		builder.addVertex(0.4375F, 0.746376F, 0.437565F, 0.25F, 6F);

	}
}
