modLoader = "javafml"
loaderVersion = "[4,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Angry-Pixel/The-Betweenlands/issues"

[[mods]]
modId="thebetweenlands"
version="${file.jarVersion}"
displayName="The Betweenlands"
#displayURL="http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1441135"
logoFile="pack.png"
authors="\n \u00A7nDevelopment Team:\u00A7r Angry Pixel\n \u00A7nContributors:\u00A7r https://github.com/Angry-Pixel/The-Betweenlands/graphs/contributors\n \u00A7nLocalization:\u00A7r TheSilverplier (fr_FR), maicol07 (it_IT), DYColdWind/RisingInIris2017/DL_Slime/lunareclipse-64/mc-kaishixiaxue (zh_CN), mcBegins2Snow (zh_TW), LIL_SUZEE/TimeConqueror/Bytegm/avale1648/Mirazhic (ru_RU), tento64/pentantan (ja_JP), NathanielFreeman/ghost (es_ES)\n \u00A7nSpecial Thanks:\u00A7r okl1001, iLexiconn, OnyxDarkNight, SanAndreasP, Stealthgert, Dylan4Ever, Vahkiti, Aginsun, Cricket, FairWolf, Fish2, Hologuard, Hwd45, Iridium616, Ivorius, KazunariAkito, Laskeri, Quintinity, RandumbDude, Robonix, Sagotomi, Sartharis, Stealthgert, Vazkii, ZeuX, calebmanley, daveyx0, kiko0804, Timinations, sam-kirby, Luohuayu, Foghrye4, asiekierka, RCXcrafter, JoshieGemFinder, Kojoley and probably many more!"
description='''
Introducing The Betweenlands... a dark and hostile environment. This large and expansive mod adds a whole new dimension to the game.'''

[[dependencies.thebetweenlands]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.17-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thebetweenlands]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"