@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.client.model.entity;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;