package thebetweenlands.api.loot;

import javax.annotation.Nullable;

import net.minecraft.util.ResourceLocation;
import net.minecraft.world.storage.loot.LootTable;

public interface ISharedLootPool {
	/**
	 * Returns the loot table location that generates the shared
	 * loot pool's items. May return null if the shared loot pool
	 * is not generated by a loot table or if the shared loot pool is a combined
	 * view of multiple shared loot pools.
	 * @return
	 */
	@Nullable
	public ResourceLocation getLootTable();

	/**
	 * Returns a loot table view of this shared loot pool
	 * that allows retrieving items from the shared loot pool.
	 * Note that the loot table view will always be frozen and
	 * not have any pools. Also keep in mind that every time loot
	 * is generated from this loot table it is removed from
	 * the shared pool!
	 * @param maxRolls The maximum number of rolls
	 * @return
	 */
	public LootTable getLootTableView(int maxRolls);

	/**
	 * Combines this shared loot pool with another shared loot pool
	 * and returns a new shared loot pool view that combines both
	 * shared loot pools.
	 * @param other Other shared loot pool to combine with this shared loot pool
	 * @return
	 */
	public ISharedLootPool combine(ISharedLootPool other);

	/**
	 * Regenerates the shared loot pool
	 */
	public void regenerate();
}
