@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.client.model.block.simulacrum;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;