package thebetweenlands.client.model.baked.flatheadmushroom2;

import thebetweenlands.util.QuadBuilder;

/**
 * Procedurally generated geometry from the 1.12.2 Tabula {@code ModelFlatHeadMushroom2}.
 * Generated by {@code convert_tabula_model_to_quadbuilder.py}.
 */
public final class FlatHeadMushroom2Geometry {

	private FlatHeadMushroom2Geometry() {
	}

	public static void build(QuadBuilder builder) {
		//stalk2
		builder.addVertex(0.258059F, 0.11042F, 0.258103F, 0.75F, 7.5F);
		builder.addVertex(0.44304F, 0.12732F, 0.232559F, 1.5F, 7.5F);
		builder.addVertex(0.473373F, -0.183385F, 0.246657F, 1.5F, 10F);
		builder.addVertex(0.288391F, -0.200285F, 0.272201F, 0.75F, 10F);
		builder.addVertex(0.282694F, 0.121244F, 0.443662F, 2.25F, 7.5F);
		builder.addVertex(0.313026F, -0.189461F, 0.45776F, 2.25F, 10F);
		builder.addVertex(0.498008F, -0.172561F, 0.432216F, 1.5F, 10F);
		builder.addVertex(0.467675F, 0.138144F, 0.418119F, 1.5F, 7.5F);
		builder.addVertex(0.288391F, -0.200285F, 0.272201F, 1.5F, 7.5F);
		builder.addVertex(0.473373F, -0.183385F, 0.246657F, 2.25F, 7.5F);
		builder.addVertex(0.498008F, -0.172561F, 0.432216F, 2.25F, 6F);
		builder.addVertex(0.313026F, -0.189461F, 0.45776F, 1.5F, 6F);
		builder.addVertex(0.258059F, 0.11042F, 0.258103F, 0.75F, 7.5F);
		builder.addVertex(0.282694F, 0.121244F, 0.443662F, 0.75F, 6F);
		builder.addVertex(0.467675F, 0.138144F, 0.418119F, 1.5F, 6F);
		builder.addVertex(0.44304F, 0.12732F, 0.232559F, 1.5F, 7.5F);
		builder.addVertex(0.44304F, 0.12732F, 0.232559F, 1.5F, 7.5F);
		builder.addVertex(0.467675F, 0.138144F, 0.418119F, 2.25F, 7.5F);
		builder.addVertex(0.498008F, -0.172561F, 0.432216F, 2.25F, 10F);
		builder.addVertex(0.473373F, -0.183385F, 0.246657F, 1.5F, 10F);
		builder.addVertex(0.258059F, 0.11042F, 0.258103F, 0.75F, 7.5F);
		builder.addVertex(0.288391F, -0.200285F, 0.272201F, 0.75F, 10F);
		builder.addVertex(0.313026F, -0.189461F, 0.45776F, 0F, 10F);
		builder.addVertex(0.282694F, 0.121244F, 0.443662F, 0F, 7.5F);
		//stalk1
		builder.addVertex(0.561144F, 0.331493F, 0.589372F, 0.75F, 1.5F);
		builder.addVertex(0.747867F, 0.314434F, 0.589372F, 1.5F, 1.5F);
		builder.addVertex(0.703128F, -0.175265F, 0.498855F, 1.5F, 5.5F);
		builder.addVertex(0.516406F, -0.158206F, 0.498855F, 0.75F, 5.5F);
		builder.addVertex(0.558056F, 0.29769F, 0.773774F, 2.25F, 1.5F);
		builder.addVertex(0.513318F, -0.192009F, 0.683257F, 2.25F, 5.5F);
		builder.addVertex(0.70004F, -0.209068F, 0.683257F, 1.5F, 5.5F);
		builder.addVertex(0.744779F, 0.280631F, 0.773774F, 1.5F, 1.5F);
		builder.addVertex(0.516406F, -0.158206F, 0.498855F, 1.5F, 1.5F);
		builder.addVertex(0.703128F, -0.175265F, 0.498855F, 2.25F, 1.5F);
		builder.addVertex(0.70004F, -0.209068F, 0.683257F, 2.25F, 0F);
		builder.addVertex(0.513318F, -0.192009F, 0.683257F, 1.5F, 0F);
		builder.addVertex(0.561144F, 0.331493F, 0.589372F, 0.75F, 1.5F);
		builder.addVertex(0.558056F, 0.29769F, 0.773774F, 0.75F, 0F);
		builder.addVertex(0.744779F, 0.280631F, 0.773774F, 1.5F, 0F);
		builder.addVertex(0.747867F, 0.314434F, 0.589372F, 1.5F, 1.5F);
		builder.addVertex(0.747867F, 0.314434F, 0.589372F, 1.5F, 1.5F);
		builder.addVertex(0.744779F, 0.280631F, 0.773774F, 2.25F, 1.5F);
		builder.addVertex(0.70004F, -0.209068F, 0.683257F, 2.25F, 5.5F);
		builder.addVertex(0.703128F, -0.175265F, 0.498855F, 1.5F, 5.5F);
		builder.addVertex(0.561144F, 0.331493F, 0.589372F, 0.75F, 1.5F);
		builder.addVertex(0.516406F, -0.158206F, 0.498855F, 0.75F, 5.5F);
		builder.addVertex(0.513318F, -0.192009F, 0.683257F, 0F, 5.5F);
		builder.addVertex(0.558056F, 0.29769F, 0.773774F, 0F, 1.5F);
		//hat1
		builder.addVertex(0.353548F, 0.463545F, 0.310367F, 3F, 12F);
		builder.addVertex(0.975956F, 0.406682F, 0.310367F, 5.5F, 12F);
		builder.addVertex(0.964595F, 0.282329F, 0.304696F, 5.5F, 13F);
		builder.addVertex(0.342187F, 0.339191F, 0.304696F, 3F, 13F);
		builder.addVertex(0.350452F, 0.429664F, 1.059595F, 8F, 12F);
		builder.addVertex(0.339091F, 0.30531F, 1.053924F, 8F, 13F);
		builder.addVertex(0.961499F, 0.248448F, 1.053924F, 5.5F, 13F);
		builder.addVertex(0.97286F, 0.372801F, 1.059595F, 5.5F, 12F);
		builder.addVertex(0.342187F, 0.339191F, 0.304696F, 5.5F, 12F);
		builder.addVertex(0.964595F, 0.282329F, 0.304696F, 8F, 12F);
		builder.addVertex(0.961499F, 0.248448F, 1.053924F, 8F, 6F);
		builder.addVertex(0.339091F, 0.30531F, 1.053924F, 5.5F, 6F);
		builder.addVertex(0.353548F, 0.463545F, 0.310367F, 3F, 12F);
		builder.addVertex(0.350452F, 0.429664F, 1.059595F, 3F, 6F);
		builder.addVertex(0.97286F, 0.372801F, 1.059595F, 5.5F, 6F);
		builder.addVertex(0.975956F, 0.406682F, 0.310367F, 5.5F, 12F);
		builder.addVertex(0.975956F, 0.406682F, 0.310367F, 5.5F, 12F);
		builder.addVertex(0.97286F, 0.372801F, 1.059595F, 8.5F, 12F);
		builder.addVertex(0.961499F, 0.248448F, 1.053924F, 8.5F, 13F);
		builder.addVertex(0.964595F, 0.282329F, 0.304696F, 5.5F, 13F);
		builder.addVertex(0.353548F, 0.463545F, 0.310367F, 3F, 12F);
		builder.addVertex(0.342187F, 0.339191F, 0.304696F, 3F, 13F);
		builder.addVertex(0.339091F, 0.30531F, 1.053924F, 0F, 13F);
		builder.addVertex(0.350452F, 0.429664F, 1.059595F, 0F, 12F);
		//hat2a
		builder.addVertex(0.230365F, 0.231684F, 0.518158F, 8.5F, 14F);
		builder.addVertex(0.540149F, 0.231466F, 0.477043F, 9.75F, 14F);
		builder.addVertex(0.539514F, 0.106535F, 0.472924F, 9.75F, 15F);
		builder.addVertex(0.229731F, 0.106754F, 0.514038F, 8.5F, 15F);
		builder.addVertex(0.238582F, 0.229601F, 0.58008F, 11F, 14F);
		builder.addVertex(0.237947F, 0.10467F, 0.575961F, 11F, 15F);
		builder.addVertex(0.547731F, 0.104452F, 0.534846F, 9.75F, 15F);
		builder.addVertex(0.548366F, 0.229382F, 0.538966F, 9.75F, 14F);
		builder.addVertex(0.229731F, 0.106754F, 0.514038F, 9.75F, 14F);
		builder.addVertex(0.539514F, 0.106535F, 0.472924F, 11F, 14F);
		builder.addVertex(0.547731F, 0.104452F, 0.534846F, 11F, 13.5F);
		builder.addVertex(0.237947F, 0.10467F, 0.575961F, 9.75F, 13.5F);
		builder.addVertex(0.230365F, 0.231684F, 0.518158F, 8.5F, 14F);
		builder.addVertex(0.238582F, 0.229601F, 0.58008F, 8.5F, 13.5F);
		builder.addVertex(0.548366F, 0.229382F, 0.538966F, 9.75F, 13.5F);
		builder.addVertex(0.540149F, 0.231466F, 0.477043F, 9.75F, 14F);
		builder.addVertex(0.540149F, 0.231466F, 0.477043F, 9.75F, 14F);
		builder.addVertex(0.548366F, 0.229382F, 0.538966F, 10F, 14F);
		builder.addVertex(0.547731F, 0.104452F, 0.534846F, 10F, 15F);
		builder.addVertex(0.539514F, 0.106535F, 0.472924F, 9.75F, 15F);
		builder.addVertex(0.230365F, 0.231684F, 0.518158F, 8.5F, 14F);
		builder.addVertex(0.229731F, 0.106754F, 0.514038F, 8.5F, 15F);
		builder.addVertex(0.237947F, 0.10467F, 0.575961F, 8.25F, 15F);
		builder.addVertex(0.238582F, 0.229601F, 0.58008F, 8.25F, 14F);
		//hat2
		builder.addVertex(0.127325F, 0.242146F, 0.216768F, 9.5F, 9F);
		builder.addVertex(0.561022F, 0.24184F, 0.159208F, 11.25F, 9F);
		builder.addVertex(0.560387F, 0.11691F, 0.155089F, 11.25F, 10F);
		builder.addVertex(0.12669F, 0.117216F, 0.212648F, 9.5F, 10F);
		builder.addVertex(0.168409F, 0.231728F, 0.52638F, 13F, 9F);
		builder.addVertex(0.167774F, 0.106798F, 0.522261F, 13F, 10F);
		builder.addVertex(0.601471F, 0.106492F, 0.464701F, 11.25F, 10F);
		builder.addVertex(0.602106F, 0.231422F, 0.468821F, 11.25F, 9F);
		builder.addVertex(0.12669F, 0.117216F, 0.212648F, 11.25F, 9F);
		builder.addVertex(0.560387F, 0.11691F, 0.155089F, 13F, 9F);
		builder.addVertex(0.601471F, 0.106492F, 0.464701F, 13F, 6.5F);
		builder.addVertex(0.167774F, 0.106798F, 0.522261F, 11.25F, 6.5F);
		builder.addVertex(0.127325F, 0.242146F, 0.216768F, 9.5F, 9F);
		builder.addVertex(0.168409F, 0.231728F, 0.52638F, 9.5F, 6.5F);
		builder.addVertex(0.602106F, 0.231422F, 0.468821F, 11.25F, 6.5F);
		builder.addVertex(0.561022F, 0.24184F, 0.159208F, 11.25F, 9F);
		builder.addVertex(0.561022F, 0.24184F, 0.159208F, 11.25F, 9F);
		builder.addVertex(0.602106F, 0.231422F, 0.468821F, 12.5F, 9F);
		builder.addVertex(0.601471F, 0.106492F, 0.464701F, 12.5F, 10F);
		builder.addVertex(0.560387F, 0.11691F, 0.155089F, 11.25F, 10F);
		builder.addVertex(0.127325F, 0.242146F, 0.216768F, 9.5F, 9F);
		builder.addVertex(0.12669F, 0.117216F, 0.212648F, 9.5F, 10F);
		builder.addVertex(0.167774F, 0.106798F, 0.522261F, 8.25F, 10F);
		builder.addVertex(0.168409F, 0.231728F, 0.52638F, 8.25F, 9F);
		//hat1a
		builder.addVertex(0.291049F, 0.466408F, 0.372802F, 5.75F, 5F);
		builder.addVertex(0.35329F, 0.460721F, 0.372802F, 6F, 5F);
		builder.addVertex(0.341929F, 0.336368F, 0.367132F, 6F, 6F);
		builder.addVertex(0.279688F, 0.342054F, 0.367132F, 5.75F, 6F);
		builder.addVertex(0.288469F, 0.438173F, 0.997159F, 6.25F, 5F);
		builder.addVertex(0.277109F, 0.31382F, 0.991489F, 6.25F, 6F);
		builder.addVertex(0.339349F, 0.308134F, 0.991489F, 6F, 6F);
		builder.addVertex(0.35071F, 0.432487F, 0.997159F, 6F, 5F);
		builder.addVertex(0.279688F, 0.342054F, 0.367132F, 6F, 5F);
		builder.addVertex(0.341929F, 0.336368F, 0.367132F, 6.25F, 5F);
		builder.addVertex(0.339349F, 0.308134F, 0.991489F, 6.25F, 0F);
		builder.addVertex(0.277109F, 0.31382F, 0.991489F, 6F, 0F);
		builder.addVertex(0.291049F, 0.466408F, 0.372802F, 5.75F, 5F);
		builder.addVertex(0.288469F, 0.438173F, 0.997159F, 5.75F, 0F);
		builder.addVertex(0.35071F, 0.432487F, 0.997159F, 6F, 0F);
		builder.addVertex(0.35329F, 0.460721F, 0.372802F, 6F, 5F);
		builder.addVertex(0.35329F, 0.460721F, 0.372802F, 6F, 5F);
		builder.addVertex(0.35071F, 0.432487F, 0.997159F, 8.5F, 5F);
		builder.addVertex(0.339349F, 0.308134F, 0.991489F, 8.5F, 6F);
		builder.addVertex(0.341929F, 0.336368F, 0.367132F, 6F, 6F);
		builder.addVertex(0.291049F, 0.466408F, 0.372802F, 5.75F, 5F);
		builder.addVertex(0.279688F, 0.342054F, 0.367132F, 5.75F, 6F);
		builder.addVertex(0.277109F, 0.31382F, 0.991489F, 3.25F, 6F);
		builder.addVertex(0.288469F, 0.438173F, 0.997159F, 3.25F, 5F);
		//hat2b
		builder.addVertex(0.181065F, 0.244186F, 0.146623F, 11.75F, 14F);
		builder.addVertex(0.490848F, 0.243968F, 0.105509F, 13F, 14F);
		builder.addVertex(0.490213F, 0.119037F, 0.101389F, 13F, 15F);
		builder.addVertex(0.18043F, 0.119256F, 0.142503F, 11.75F, 15F);
		builder.addVertex(0.189281F, 0.242102F, 0.208545F, 14.25F, 14F);
		builder.addVertex(0.188647F, 0.117172F, 0.204426F, 14.25F, 15F);
		builder.addVertex(0.49843F, 0.116953F, 0.163312F, 13F, 15F);
		builder.addVertex(0.499065F, 0.241884F, 0.167431F, 13F, 14F);
		builder.addVertex(0.18043F, 0.119256F, 0.142503F, 13F, 14F);
		builder.addVertex(0.490213F, 0.119037F, 0.101389F, 14.25F, 14F);
		builder.addVertex(0.49843F, 0.116953F, 0.163312F, 14.25F, 13.5F);
		builder.addVertex(0.188647F, 0.117172F, 0.204426F, 13F, 13.5F);
		builder.addVertex(0.181065F, 0.244186F, 0.146623F, 11.75F, 14F);
		builder.addVertex(0.189281F, 0.242102F, 0.208545F, 11.75F, 13.5F);
		builder.addVertex(0.499065F, 0.241884F, 0.167431F, 13F, 13.5F);
		builder.addVertex(0.490848F, 0.243968F, 0.105509F, 13F, 14F);
		builder.addVertex(0.490848F, 0.243968F, 0.105509F, 13F, 14F);
		builder.addVertex(0.499065F, 0.241884F, 0.167431F, 13.25F, 14F);
		builder.addVertex(0.49843F, 0.116953F, 0.163312F, 13.25F, 15F);
		builder.addVertex(0.490213F, 0.119037F, 0.101389F, 13F, 15F);
		builder.addVertex(0.181065F, 0.244186F, 0.146623F, 11.75F, 14F);
		builder.addVertex(0.18043F, 0.119256F, 0.142503F, 11.75F, 15F);
		builder.addVertex(0.188647F, 0.117172F, 0.204426F, 11.5F, 15F);
		builder.addVertex(0.189281F, 0.242102F, 0.208545F, 11.5F, 14F);
		//hat1b
		builder.addVertex(0.975698F, 0.403859F, 0.372802F, 11.5F, 5F);
		builder.addVertex(1.037938F, 0.398172F, 0.372802F, 11.75F, 5F);
		builder.addVertex(1.026578F, 0.273819F, 0.367132F, 11.75F, 6F);
		builder.addVertex(0.964337F, 0.279505F, 0.367132F, 11.5F, 6F);
		builder.addVertex(0.973118F, 0.375624F, 0.997159F, 12F, 5F);
		builder.addVertex(0.961757F, 0.251271F, 0.991489F, 12F, 6F);
		builder.addVertex(1.023998F, 0.245585F, 0.991489F, 11.75F, 6F);
		builder.addVertex(1.035359F, 0.369938F, 0.997159F, 11.75F, 5F);
		builder.addVertex(0.964337F, 0.279505F, 0.367132F, 11.75F, 5F);
		builder.addVertex(1.026578F, 0.273819F, 0.367132F, 12F, 5F);
		builder.addVertex(1.023998F, 0.245585F, 0.991489F, 12F, 0F);
		builder.addVertex(0.961757F, 0.251271F, 0.991489F, 11.75F, 0F);
		builder.addVertex(0.975698F, 0.403859F, 0.372802F, 11.5F, 5F);
		builder.addVertex(0.973118F, 0.375624F, 0.997159F, 11.5F, 0F);
		builder.addVertex(1.035359F, 0.369938F, 0.997159F, 11.75F, 0F);
		builder.addVertex(1.037938F, 0.398172F, 0.372802F, 11.75F, 5F);
		builder.addVertex(1.037938F, 0.398172F, 0.372802F, 11.75F, 5F);
		builder.addVertex(1.035359F, 0.369938F, 0.997159F, 14.25F, 5F);
		builder.addVertex(1.023998F, 0.245585F, 0.991489F, 14.25F, 6F);
		builder.addVertex(1.026578F, 0.273819F, 0.367132F, 11.75F, 6F);
		builder.addVertex(0.975698F, 0.403859F, 0.372802F, 11.5F, 5F);
		builder.addVertex(0.964337F, 0.279505F, 0.367132F, 11.5F, 6F);
		builder.addVertex(0.961757F, 0.251271F, 0.991489F, 9F, 6F);
		builder.addVertex(0.973118F, 0.375624F, 0.997159F, 9F, 5F);
	}
}
