@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.common.herblore.aspect;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;