package thebetweenlands.common.datagen;

import net.minecraft.Util;
import net.minecraft.core.component.DataComponents;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.LanguageProvider;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredItem;
import org.apache.commons.lang3.StringUtils;
import thebetweenlands.api.aspect.AspectType;
import thebetweenlands.common.TheBetweenlands;
import thebetweenlands.common.registries.AspectRegistry;
import thebetweenlands.common.registries.BlockRegistry;
import thebetweenlands.common.registries.ItemRegistry;

public class BetweenlandsLangProvider extends LanguageProvider {
	public BetweenlandsLangProvider(PackOutput output) {
		super(output, TheBetweenlands.ID, "en_us");
	}

	@Override
	protected void addTranslations() {
		this.add("itemGroup.thebetweenlands.blocks", "The Betweenlands Blocks");
		this.add("itemGroup.thebetweenlands.items", "The Betweenlands Items");
		this.add("itemGroup.thebetweenlands.gear", "The Betweenlands Gear");
		this.add("itemGroup.thebetweenlands.specials", "The Betweenlands Specials");
		this.add("itemGroup.thebetweenlands.plants", "The Betweenlands Plants");
		this.add("itemGroup.thebetweenlands.herblore", "The Betweenlands Herblore");

		this.addBlock(BlockRegistry.ALEMBIC, "Alembic");
		this.addBlock(BlockRegistry.ALGAE, "Algae");
		this.addBlock(BlockRegistry.ANCIENT_REMNANT_BLOCK, "Block of Ancient Remnant");
		this.addBlock(BlockRegistry.ANGRY_BETWEENSTONE, "Angry Betweenstone");
		this.addBlock(BlockRegistry.ANIMATOR, "Animator");
		this.addBlock(BlockRegistry.AQUA_MIDDLE_GEM_BLOCK, "Block of Aqua Middle Gem");
		this.addBlock(BlockRegistry.AQUA_MIDDLE_GEM_ORE, "Aqua Middle Gem Ore");
		this.addBlock(BlockRegistry.ARROW_ARUM, "Arrow Arum");
		this.addBlock(BlockRegistry.BARNACLE, "Barnacle");
		this.addBlock(BlockRegistry.BEAM_LENS_SUPPORT, "Beam Lens Support");
		this.addBlock(BlockRegistry.BEAM_ORIGIN, "Beam Origin");
		this.addBlock(BlockRegistry.BEAM_RELAY, "Beam Relay");
		this.addBlock(BlockRegistry.BEAM_TUBE, "Beam Tube");
		this.addBlock(BlockRegistry.BETWEENLANDS_BEDROCK, "Betweenlands Bedrock");
		this.addBlock(BlockRegistry.BETWEENSTONE, "Betweenstone");
		this.addBlock(BlockRegistry.BETWEENSTONE_BRICK_SLAB, "Betweenstone Brick Slab");
		this.addBlock(BlockRegistry.BETWEENSTONE_BRICK_STAIRS, "Betweenstone Brick Stairs");
		this.addBlock(BlockRegistry.BETWEENSTONE_BRICK_WALL, "Betweenstone Brick Wall");
		this.addBlock(BlockRegistry.BETWEENSTONE_BRICKS, "Betweenstone Bricks");
		this.addBlock(BlockRegistry.BETWEENSTONE_BUTTON, "Betweenstone Button");
		this.addBlock(BlockRegistry.BETWEENSTONE_PEBBLE, "Betweenstone Pebble");
		this.addBlock(BlockRegistry.BETWEENSTONE_PILLAR, "Betweenstone Pillar");
		this.addBlock(BlockRegistry.BETWEENSTONE_PRESSURE_PLATE, "Betweenstone Pressure Plate");
		this.addBlock(BlockRegistry.BETWEENSTONE_SLAB, "Betweenstone Slab");
		this.addBlock(BlockRegistry.BETWEENSTONE_STAIRS, "Betweenstone Stairs");
		this.addBlock(BlockRegistry.BETWEENSTONE_TILES, "Betweenstone Tiles");
		this.addBlock(BlockRegistry.BETWEENSTONE_WALL, "Betweenstone Wall");
		this.addBlock(BlockRegistry.BLACK_HAT_MUSHROOM, "Black Hat Mushroom");
		this.addBlock(BlockRegistry.BLACK_ICE, "Black Ice");
		this.addBlock(BlockRegistry.BLACK_PRESENT, "Black Present");
		this.addBlock(BlockRegistry.BLADDERWORT_FLOWER, "Bladderwort Flower");
		this.addBlock(BlockRegistry.BLADDERWORT_STALK, "Bladderwort Stalk");
		this.addBlock(BlockRegistry.BLUE_BAUBLE, "Blue Bauble");
		this.addBlock(BlockRegistry.BLUE_EYED_GRASS, "Blue-Eyed Grass");
		this.addBlock(BlockRegistry.BLUE_IRIS, "Blue Iris");
		this.addBlock(BlockRegistry.BLUE_PRESENT, "Blue Present");
		this.addBlock(BlockRegistry.BOG_BEAN_FLOWER, "Bog Bean Flower");
		this.addBlock(BlockRegistry.BOG_BEAN_STALK, "Bog Bean Stalk");
		this.addBlock(BlockRegistry.BONE_NESTING_BLOCK, "Nesting Block");
		this.addBlock(BlockRegistry.BONESET, "Boneset");
		this.addBlock(BlockRegistry.BOTTLE_BRUSH_GRASS, "Bottle Brush Grass");
		this.addBlock(BlockRegistry.BOTTOM_SPIRIT_TREE_LEAVES, "Lower Spirit Tree Leaves");
		this.addBlock(BlockRegistry.BRAZIER, "Brazier");
		this.addBlock(BlockRegistry.BROKEN_MUD_TILES, "Broken Mud Tiles");
		this.addBlock(BlockRegistry.BROOMSEDGE, "Broomsedge");
		this.addBlock(BlockRegistry.BROWN_PRESENT, "Brown Present");
		this.addBlock(BlockRegistry.BROWN_RUST_FILTERED_SILT_GLASS_BLOCK, "Brown Rust Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.BROWN_RUST_MUD_BRICK_SHINGLE_SLAB, "Brown Rust Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.BROWN_RUST_MUD_BRICK_SHINGLE_STAIRS, "Brown Rust Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.BROWN_RUST_MUD_BRICK_SHINGLES, "Brown Rust Mud Brick Shingles");
		this.addBlock(BlockRegistry.BROWN_RUST_REED_MAT, "Brown Rust Reed Mat");
		this.addBlock(BlockRegistry.BROWN_RUST_SAMITE, "Brown Rust Samite");
		this.addBlock(BlockRegistry.BROWN_RUST_SAMITE_CANVAS_PANEL, "Brown Rust Samite Canvas Panel");
		this.addBlock(BlockRegistry.BULB_CAPPED_MUSHROOM, "Bulb-Capped Mushroom");
		this.addBlock(BlockRegistry.BULB_CAPPED_MUSHROOM_CAP, "Bulb-Capped Mushroom Cap");
		this.addBlock(BlockRegistry.BULB_CAPPED_MUSHROOM_STALK, "Bulb-Capped Mushroom Stalk");
		this.addBlock(BlockRegistry.BUTTON_BUSH, "Button Bush");
		this.addBlock(BlockRegistry.CADMIUM_GREEN_FILTERED_SILT_GLASS_BLOCK, "Cadmium Green Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.CADMIUM_GREEN_MUD_BRICK_SHINGLE_SLAB, "Cadmium Green Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.CADMIUM_GREEN_MUD_BRICK_SHINGLE_STAIRS, "Cadmium Green Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.CADMIUM_GREEN_MUD_BRICK_SHINGLES, "Cadmium Green Mud Brick Shingles");
		this.addBlock(BlockRegistry.CADMIUM_GREEN_REED_MAT, "Cadmium Green Reed Mat");
		this.addBlock(BlockRegistry.CADMIUM_GREEN_SAMITE, "Cadmium Green Samite");
		this.addBlock(BlockRegistry.CADMIUM_GREEN_SAMITE_CANVAS_PANEL, "Cadmium Green Samite Canvas Panel");
		this.addBlock(BlockRegistry.CAMELOT_MAGENTA_FILTERED_SILT_GLASS_BLOCK, "Camelot Magenta Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.CAMELOT_MAGENTA_MUD_BRICK_SHINGLE_SLAB, "Camelot Magenta Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.CAMELOT_MAGENTA_MUD_BRICK_SHINGLE_STAIRS, "Camelot Magenta Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.CAMELOT_MAGENTA_MUD_BRICK_SHINGLES, "Camelot Magenta Mud Brick Shingles");
		this.addBlock(BlockRegistry.CAMELOT_MAGENTA_REED_MAT, "Camelot Magenta Reed Mat");
		this.addBlock(BlockRegistry.CAMELOT_MAGENTA_SAMITE, "Camelot Magenta Samite");
		this.addBlock(BlockRegistry.CAMELOT_MAGENTA_SAMITE_CANVAS_PANEL, "Camelot Magenta Samite Canvas Panel");
		this.addBlock(BlockRegistry.CARDINAL_FLOWER, "Cardinal Flower");
		this.addBlock(BlockRegistry.CARIBBEAN_GREEN_FILTERED_SILT_GLASS_BLOCK, "Caribbean Green Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.CARIBBEAN_GREEN_MUD_BRICK_SHINGLE_SLAB, "Caribbean Green Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.CARIBBEAN_GREEN_MUD_BRICK_SHINGLE_STAIRS, "Caribbean Green Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.CARIBBEAN_GREEN_MUD_BRICK_SHINGLES, "Caribbean Green Mud Brick Shingles");
		this.addBlock(BlockRegistry.CARIBBEAN_GREEN_REED_MAT, "Caribbean Green Reed Mat");
		this.addBlock(BlockRegistry.CARIBBEAN_GREEN_SAMITE, "Caribbean Green Samite");
		this.addBlock(BlockRegistry.CARIBBEAN_GREEN_SAMITE_CANVAS_PANEL, "Caribbean Green Samite Canvas Panel");
		this.addBlock(BlockRegistry.CARVED_MUD_BRICK_EDGE, "Carved Mud Brick Edge");
		this.addBlock(BlockRegistry.CARVED_MUD_BRICKS, "Carved Mud Bricks");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_1, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_2, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_3, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_4, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_5, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_6, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_7, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_8, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_9, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_10, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_11, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_12, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_13, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_14, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_15, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CARVED_ROTTEN_BARK_16, "Carved Rotten Bark");
		this.addBlock(BlockRegistry.CATTAIL, "Cattail");
		this.addBlock(BlockRegistry.CAVE_GRASS, "Cave Grass");
		this.addBlock(BlockRegistry.CAVE_MOSS, "Cave Moss");
		this.addBlock(BlockRegistry.CAVE_MOSS_PLANT, "Cave Moss Plant");
		this.addBlock(BlockRegistry.CAVING_ROPE_LIGHT, "Caving Rope Light");
		this.addBlock(BlockRegistry.CENSER, "Censer");
		this.addBlock(BlockRegistry.CHAMPAGNE_FILTERED_SILT_GLASS_BLOCK, "Champagne Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.CHAMPAGNE_MUD_BRICK_SHINGLE_SLAB, "Champagne Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.CHAMPAGNE_MUD_BRICK_SHINGLE_STAIRS, "Champagne Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.CHAMPAGNE_MUD_BRICK_SHINGLES, "Champagne Mud Brick Shingles");
		this.addBlock(BlockRegistry.CHAMPAGNE_REED_MAT, "Champagne Reed Mat");
		this.addBlock(BlockRegistry.CHAMPAGNE_SAMITE, "Champagne Samite");
		this.addBlock(BlockRegistry.CHAMPAGNE_SAMITE_CANVAS_PANEL, "Champagne Samite Canvas Panel");
		this.addBlock(BlockRegistry.CHIP_PATH, "Weedwood Chip Path");
		this.addBlock(BlockRegistry.CHISELED_BETWEENSTONE, "Chiseled Betweenstone");
		this.addBlock(BlockRegistry.CHISELED_CRAGROCK, "Chiseled Cragrock");
		this.addBlock(BlockRegistry.CHISELED_LIMESTONE, "Chiseled Limestone");
		this.addBlock(BlockRegistry.CHISELED_PITSTONE, "Chiseled Pitstone");
		this.addBlock(BlockRegistry.CHISELED_SCABYST_1, "Chiseled Scabyst");
		this.addBlock(BlockRegistry.CHISELED_SCABYST_2, "Chiseled Scabyst");
		this.addBlock(BlockRegistry.CHISELED_SCABYST_3, "Chiseled Scabyst");
		this.addBlock(BlockRegistry.CLIMBABLE_MUD_BRICKS, "Climbable Mud Bricks");
		this.addBlock(BlockRegistry.COARSE_SWAMP_DIRT, "Coarse Swamp Dirt");
		this.addBlock(BlockRegistry.COMPACTED_MUD, "Compacted Mud");
		this.addBlock(BlockRegistry.COMPACTED_MUD_MIRAGE, "Compacted Mud");
		this.addBlock(BlockRegistry.COMPACTED_MUD_SLAB, "Compacted Mud Slab");
		this.addBlock(BlockRegistry.COMPACTED_MUD_SLOPE, "Compacted Mud Slope");
		this.addBlock(BlockRegistry.COMPOST_BIN, "Compost Bin");
		this.addBlock(BlockRegistry.COMPOST_BLOCK, "Compost Block");
		this.addBlock(BlockRegistry.CONNECTED_AMATE_PAPER_PANE, "Connected Amate Paper Pane");
		this.addBlock(BlockRegistry.COPPER_IRIS, "Copper Iris");
		this.addBlock(BlockRegistry.CORRUPT_BETWEENSTONE, "Corrupt Betweenstone");
		this.addBlock(BlockRegistry.CRAB_POT, "Crab Pot");
		this.addBlock(BlockRegistry.CRAB_POT_FILTER, "Crab Pot Filter");
		this.addBlock(BlockRegistry.CRACKED_BETWEENSTONE_BRICK_SLAB, "Cracked Betweenstone Brick Slab");
		this.addBlock(BlockRegistry.CRACKED_BETWEENSTONE_BRICK_STAIRS, "Cracked Betweenstone Brick Stairs");
		this.addBlock(BlockRegistry.CRACKED_BETWEENSTONE_BRICK_WALL, "Cracked Betweenstone Brick Wall");
		this.addBlock(BlockRegistry.CRACKED_BETWEENSTONE_BRICKS, "Cracked Betweenstone Bricks");
		this.addBlock(BlockRegistry.CRACKED_BETWEENSTONE_TILES, "Cracked Betweenstone Tiles");
		this.addBlock(BlockRegistry.CRACKED_CHISELED_CRAGROCK, "Cracked Chiseled Cragrock");
		this.addBlock(BlockRegistry.CRACKED_CRAGROCK_BRICKS, "Cracked Cragrock Bricks");
		this.addBlock(BlockRegistry.CRACKED_CRAGROCK_TILES, "Cracked Cragrock Tiles");
		this.addBlock(BlockRegistry.CRACKED_DECAYED_MUD_TILES, "Cracked Decayed Mud Tiles");
		this.addBlock(BlockRegistry.CRACKED_LIMESTONE_BRICKS, "Cracked Limestone Bricks");
		this.addBlock(BlockRegistry.CRACKED_MUD_TILES, "Cracked Mud Tiles");
		this.addBlock(BlockRegistry.CRAGROCK, "Cragrock");
		this.addBlock(BlockRegistry.CRAGROCK_BRICK_SLAB, "Cragrock Brick Slab");
		this.addBlock(BlockRegistry.CRAGROCK_BRICK_STAIRS, "Cragrock Brick Stairs");
		this.addBlock(BlockRegistry.CRAGROCK_BRICK_WALL, "Cragrock Brick Wall");
		this.addBlock(BlockRegistry.CRAGROCK_BRICKS, "Cragrock Bricks");
		this.addBlock(BlockRegistry.CRAGROCK_PILLAR, "Cragrock Pillar");
		this.addBlock(BlockRegistry.CRAGROCK_SLAB, "Cragrock Slab");
		this.addBlock(BlockRegistry.CRAGROCK_STAIRS, "Cragrock Stairs");
		this.addBlock(BlockRegistry.CRAGROCK_TILES, "Cragrock Tiles");
		this.addBlock(BlockRegistry.CRAGROCK_WALL, "Cragrock Wall");
		this.addBlock(BlockRegistry.CRAWLER_DUNGEON_DOOR_RUNES, "Dungeon Door");
		this.addBlock(BlockRegistry.CRIMSON_MIDDLE_GEM_BLOCK, "Block of Crimson Middle Gem");
		this.addBlock(BlockRegistry.CRIMSON_MIDDLE_GEM_ORE, "Crimson Middle Gem Ore");
		this.addBlock(BlockRegistry.CRYPTWEED, "Cryptweed");
		this.addBlock(BlockRegistry.CRYPTWEED_PLANT, "Cryptweed Plant");
		this.addBlock(BlockRegistry.CYAN_BAUBLE, "Cyan Bauble");
		this.addBlock(BlockRegistry.CYAN_PRESENT, "Cyan Present");
		this.addBlock(BlockRegistry.DAMP_TORCH, "Damp Torch");
		this.addBlock(BlockRegistry.DEAD_GRASS, "Dead Grass");
		this.addBlock(BlockRegistry.DEAD_LICHEN, "Dead Lichen");
		this.addBlock(BlockRegistry.DEAD_MOSS, "Dead Moss");
		this.addBlock(BlockRegistry.DEAD_WEEDWOOD_BUSH, "Dead Weedwood Bush");
		this.addBlock(BlockRegistry.DECAY_INFESTED_WEEDWOOD_BUSH, "Decay Infested Weedwood Bush");
		this.addBlock(BlockRegistry.DECAY_PIT_CONTROL, "Pit of Decay");
		this.addBlock(BlockRegistry.DECAY_PIT_GROUND_CHAIN, "Pit of Decay Chain");
		this.addBlock(BlockRegistry.DECAY_PIT_HANGING_CHAIN, "Pit of Decay Chain");
		this.addBlock(BlockRegistry.DECAYED_MUD_TILES, "Decayed Mud Tiles");
		this.addBlock(BlockRegistry.DEEP_WATER_CORAL, "Deep Water Coral");
		this.addBlock(BlockRegistry.DEEP_WATER_CORAL_BLOCK, "Deep Water Coral Block");
		this.addBlock(BlockRegistry.DEEPMAN_SIMULACRUM_1, "Deepman Simulacrum");
		this.addBlock(BlockRegistry.DEEPMAN_SIMULACRUM_2, "Deepman Simulacrum");
		this.addBlock(BlockRegistry.DEEPMAN_SIMULACRUM_3, "Deepman Simulacrum");
		this.addBlock(BlockRegistry.DIAGONAL_ENERGY_BARRIER, "Energy Barrier");
		this.addBlock(BlockRegistry.DOTTED_SCABYST_PITSTONE, "Scabyst Lined Pitstone");
		this.addBlock(BlockRegistry.DRUID_ALTAR, "Dark Druid Altar");
		this.addBlock(BlockRegistry.DRUID_STONE_1, "Rune Stone");
		this.addBlock(BlockRegistry.DRUID_STONE_2, "Rune Stone");
		this.addBlock(BlockRegistry.DRUID_STONE_3, "Rune Stone");
		this.addBlock(BlockRegistry.DRUID_STONE_4, "Rune Stone");
		this.addBlock(BlockRegistry.DRUID_STONE_5, "Rune Stone");
		this.addBlock(BlockRegistry.DRUID_STONE_6, "Rune Stone");
		this.addBlock(BlockRegistry.DUAL_SULFUR_FURNACE, "Dual Sulfur Furnace");
		this.addBlock(BlockRegistry.DUG_SWAMP_DIRT, "Dug Swamp Dirt");
		this.addBlock(BlockRegistry.DUG_SWAMP_GRASS, "Dug Swamp Grass");
		this.addBlock(BlockRegistry.DULL_LAVENDER_FILTERED_SILT_GLASS_BLOCK, "Dull Lavender Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.DULL_LAVENDER_MUD_BRICK_SHINGLE_SLAB, "Dull Lavender Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.DULL_LAVENDER_MUD_BRICK_SHINGLE_STAIRS, "Dull Lavender Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.DULL_LAVENDER_MUD_BRICK_SHINGLES, "Dull Lavender Mud Brick Shingles");
		this.addBlock(BlockRegistry.DULL_LAVENDER_REED_MAT, "Dull Lavender Reed Mat");
		this.addBlock(BlockRegistry.DULL_LAVENDER_SAMITE, "Dull Lavender Samite");
		this.addBlock(BlockRegistry.DULL_LAVENDER_SAMITE_CANVAS_PANEL, "Dull Lavender Samite Canvas Panel");
		this.addBlock(BlockRegistry.DUNGEON_DOOR_COMBINATION, "Dungeon Door Code");
		this.addBlock(BlockRegistry.DUNGEON_DOOR_RUNES, "Dungeon Door");
		this.addBlock(BlockRegistry.DUNGEON_WALL_CANDLE, "Wall Candle");
		this.addBlock(BlockRegistry.EDGE_LEAF, "Edge Leaf");
		this.addBlock(BlockRegistry.EDGE_MOSS, "Edge Moss");
		this.addBlock(BlockRegistry.EDGE_SHROOM, "Edge Shroom");
		this.addBlock(BlockRegistry.ELM_CYAN_FILTERED_SILT_GLASS_BLOCK, "Elm Cyan Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.ELM_CYAN_MUD_BRICK_SHINGLE_SLAB, "Elm Cyan Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.ELM_CYAN_MUD_BRICK_SHINGLE_STAIRS, "Elm Cyan Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.ELM_CYAN_MUD_BRICK_SHINGLES, "Elm Cyan Mud Brick Shingles");
		this.addBlock(BlockRegistry.ELM_CYAN_REED_MAT, "Elm Cyan Reed Mat");
		this.addBlock(BlockRegistry.ELM_CYAN_SAMITE, "Elm Cyan Samite");
		this.addBlock(BlockRegistry.ELM_CYAN_SAMITE_CANVAS_PANEL, "Elm Cyan Samite Canvas Panel");
		this.addBlock(BlockRegistry.ENERGY_BARRIER, "Energy Barrier");
		this.addBlock(BlockRegistry.EXTINGUISHED_SULFUR_TORCH, "Extinguished Sulfur Torch");
		this.addBlock(BlockRegistry.FALLEN_LEAVES, "Fallen Leaves");
		this.addBlock(BlockRegistry.FILTERED_SILT, "Filtered Silt");
		this.addBlock(BlockRegistry.FILTERED_SILT_GLASS, "Filtered Silt Glass");
		this.addBlock(BlockRegistry.FILTERED_SILT_GLASS_JAR, "Filtered Silt Glass Jar");
		this.addBlock(BlockRegistry.FILTERED_SILT_GLASS_PANE, "Filtered Silt Glass Pane");
		this.addBlock(BlockRegistry.FINE_LATTICE, "Fine Lattice");
		this.addBlockWithDesc(BlockRegistry.FISH_TRIMMING_TABLE, "Trimming Table", "Uses a bone axe to chop caught fish and crabs.");
		this.addBlock(BlockRegistry.FISHING_TACKLE_BOX, "Fishing Tackle Box");
		this.addBlock(BlockRegistry.FLATHEAD_MUSHROOM, "Flathead Mushroom");
		this.addBlock(BlockRegistry.FLOWERED_NETTLE, "Flowered Nettle");
		this.addBlock(BlockRegistry.GECKO_CAGE, "Gecko Cage");
		this.addBlock(BlockRegistry.GIANT_ROOT, "Giant Root");
		this.addBlock(BlockRegistry.GIANT_ROOT_DOOR, "Giant Root Door");
		this.addBlock(BlockRegistry.GIANT_ROOT_FENCE, "Giant Root Fence");
		this.addBlock(BlockRegistry.GIANT_ROOT_FENCE_GATE, "Giant Root Fence Gate");
		this.addBlock(BlockRegistry.GIANT_ROOT_PLANKS, "Giant Root Planks");
		this.addBlock(BlockRegistry.GIANT_ROOT_SLAB, "Giant Root Slab");
		this.addBlock(BlockRegistry.GIANT_ROOT_STAIRS, "Giant Root Stairs");
		this.addBlock(BlockRegistry.GIANT_ROOT_TRAPDOOR, "Giant Root Trapdoor");
		this.addBlock(BlockRegistry.GLOWING_BETWEENSTONE_TILE, "Glowing Betweenstone Tile");
		this.addBlock(BlockRegistry.GLOWING_GOOP, "Glowing Goop");
		this.addBlock(BlockRegistry.GLOWING_SMOOTH_CRAGROCK, "Glowing Smooth Cragrock");
		this.addBlock(BlockRegistry.GOLDEN_CLUB_FLOWER, "Golden Club Flower");
		this.addBlock(BlockRegistry.GOLDEN_CLUB_STALK, "Golden Club Stalk");
		this.addBlock(BlockRegistry.GRAY_PRESENT, "Gray Present");
		this.addBlock(BlockRegistry.GREEN_ASPECT_VIAL, "Green Aspect Vial");
		this.addBlock(BlockRegistry.GREEN_BAUBLE, "Green Bauble");
		this.addBlock(BlockRegistry.GREEN_DENTROTHYST, "Green Dentrothyst");
		this.addBlock(BlockRegistry.GREEN_MIDDLE_GEM_BLOCK, "Block of Green Middle Gem");
		this.addBlock(BlockRegistry.GREEN_MIDDLE_GEM_ORE, "Green Middle Gem Ore");
		this.addBlock(BlockRegistry.GREEN_PRESENT, "Green Present");
		this.addBlock(BlockRegistry.GROUND_ITEM, "Ground Item");
		this.addBlock(BlockRegistry.GRUB_HUB, "Grub Hub");
		this.addBlock(BlockRegistry.GRUB_INFESTED_WEEDWOOD_BUSH, "Grub Infested Weedwood Bush");
		this.addBlock(BlockRegistry.HANGER, "Hanger");
		this.addBlock(BlockRegistry.HEARTHGROVE_BARK, "Hearthgrove Bark");
		this.addBlock(BlockRegistry.HEARTHGROVE_DOOR, "Hearthgrove Door");
		this.addBlock(BlockRegistry.HEARTHGROVE_FENCE, "Hearthgrove Fence");
		this.addBlock(BlockRegistry.HEARTHGROVE_FENCE_GATE, "Hearthgrove Fence Gate");
		this.addBlock(BlockRegistry.HEARTHGROVE_LEAVES, "Hearthgrove Leaves");
		this.addBlock(BlockRegistry.HEARTHGROVE_LOG, "Hearthgrove Log");
		this.addBlock(BlockRegistry.HEARTHGROVE_PLANKS, "Hearthgrove Planks");
		this.addBlock(BlockRegistry.HEARTHGROVE_SLAB, "Hearthgrove Slab");
		this.addBlock(BlockRegistry.HEARTHGROVE_STAIRS, "Hearthgrove Stairs");
		this.addBlock(BlockRegistry.HEARTHGROVE_TRAPDOOR, "Hearthgrove Trapdoor");
		this.addBlock(BlockRegistry.HOLLOW_LOG, "Hollow Log");
		this.addBlock(BlockRegistry.HORIZONTAL_SCABYST_PITSTONE, "Scabyst Lined Pitstone");
		this.addBlock(BlockRegistry.INACTIVE_GLOWING_SMOOTH_CRAGROCK, "Inactive Glowing Smooth Cragrock");
		this.addBlock(BlockRegistry.INFUSER, "Infuser");
		this.addBlock(BlockRegistry.ITEM_CAGE, "Item Cage");
		this.addBlock(BlockRegistry.ITEM_SHELF, "Item Shelf");
		this.addBlock(BlockRegistry.LAKE_CAVERN_SIMULACRUM_1, "Lake Cavern Simulacrum");
		this.addBlock(BlockRegistry.LAKE_CAVERN_SIMULACRUM_2, "Lake Cavern Simulacrum");
		this.addBlock(BlockRegistry.LAKE_CAVERN_SIMULACRUM_3, "Lake Cavern Simulacrum");
		this.addBlock(BlockRegistry.LATTICE, "Lattice");
		this.addBlock(BlockRegistry.LAVENDER_BLUE_FILTERED_SILT_GLASS_BLOCK, "Lavender Blue Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.LAVENDER_BLUE_MUD_BRICK_SHINGLE_SLAB, "Lavender Blue Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.LAVENDER_BLUE_MUD_BRICK_SHINGLE_STAIRS, "Lavender Blue Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.LAVENDER_BLUE_MUD_BRICK_SHINGLES, "Lavender Blue Mud Brick Shingles");
		this.addBlock(BlockRegistry.LAVENDER_BLUE_REED_MAT, "Lavender Blue Reed Mat");
		this.addBlock(BlockRegistry.LAVENDER_BLUE_SAMITE, "Lavender Blue Samite");
		this.addBlock(BlockRegistry.LAVENDER_BLUE_SAMITE_CANVAS_PANEL, "Lavender Blue Samite Canvas Panel");
		this.addBlock(BlockRegistry.LICHEN, "Lichen");
		this.addBlock(BlockRegistry.LIFE_CRYSTAL_ORE_STALACTITE, "Life Crystal Stalactite");
		this.addBlock(BlockRegistry.LIFE_CRYSTAL_STALACTITE, "Life Crystal Stalactite");
		this.addBlock(BlockRegistry.LIGHT_BLUE_BAUBLE, "Light Blue Bauble");
		this.addBlock(BlockRegistry.LIGHT_BLUE_PRESENT, "Light Blue Present");
		this.addBlock(BlockRegistry.LIGHT_GRAY_PRESENT, "Light Gray Present");
		this.addBlock(BlockRegistry.LIME_PRESENT, "Lime Present");
		this.addBlock(BlockRegistry.LIMESTONE, "Limestone");
		this.addBlock(BlockRegistry.LIMESTONE_BRICK_SLAB, "Limestone Brick Slab");
		this.addBlock(BlockRegistry.LIMESTONE_BRICK_STAIRS, "Limestone Brick Stairs");
		this.addBlock(BlockRegistry.LIMESTONE_BRICK_WALL, "Limestone Brick Wall");
		this.addBlock(BlockRegistry.LIMESTONE_BRICKS, "Limestone Bricks");
		this.addBlock(BlockRegistry.LIMESTONE_PILLAR, "Limestone Pillar");
		this.addBlock(BlockRegistry.LIMESTONE_SLAB, "Limestone Slab");
		this.addBlock(BlockRegistry.LIMESTONE_STAIRS, "Limestone Stairs");
		this.addBlock(BlockRegistry.LIMESTONE_TILES, "Limestone Tiles");
		this.addBlock(BlockRegistry.LIMESTONE_WALL, "Limestone Wall");
		this.addBlock(BlockRegistry.LOOT_POT_1, "Pot of Chance");
		this.addBlock(BlockRegistry.LOOT_POT_2, "Pot of Chance");
		this.addBlock(BlockRegistry.LOOT_POT_3, "Pot of Chance");
		this.addBlock(BlockRegistry.LOOT_URN_1, "Urn of Chance");
		this.addBlock(BlockRegistry.LOOT_URN_2, "Urn of Chance");
		this.addBlock(BlockRegistry.LOOT_URN_3, "Urn of Chance");
		this.addBlock(BlockRegistry.LYESTONE, "Lyestone");
		this.addBlock(BlockRegistry.MAGENTA_BAUBLE, "Magenta Bauble");
		this.addBlock(BlockRegistry.MAGENTA_PRESENT, "Magenta Present");
		this.addBlock(BlockRegistry.MAROON_FILTERED_SILT_GLASS_BLOCK, "Maroon Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.MAROON_MUD_BRICK_SHINGLE_SLAB, "Maroon Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.MAROON_MUD_BRICK_SHINGLE_STAIRS, "Maroon Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.MAROON_MUD_BRICK_SHINGLES, "Maroon Mud Brick Shingles");
		this.addBlock(BlockRegistry.MAROON_REED_MAT, "Maroon Reed Mat");
		this.addBlock(BlockRegistry.MAROON_SAMITE, "Maroon Samite");
		this.addBlock(BlockRegistry.MAROON_SAMITE_CANVAS_PANEL, "Maroon Samite Canvas Panel");
		this.addBlock(BlockRegistry.MARSH_HIBISCUS, "Marsh Hibiscus");
		this.addBlock(BlockRegistry.MARSH_MALLOW, "Marsh Mallow");
		this.addBlock(BlockRegistry.MARSH_MARIGOLD_FLOWER, "Marsh Marigold Flower");
		this.addBlock(BlockRegistry.MARSH_MARIGOLD_STALK, "Marsh Marigold Stalk");
		this.addBlock(BlockRegistry.MIDDLE_SPIRIT_TREE_LEAVES, "Middle Spirit Tree Leaves");
		this.addBlock(BlockRegistry.MIDNIGHT_PURPLE_FILTERED_SILT_GLASS_BLOCK, "Midnight Purple Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.MIDNIGHT_PURPLE_MUD_BRICK_SHINGLE_SLAB, "Midnight Purple Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.MIDNIGHT_PURPLE_MUD_BRICK_SHINGLE_STAIRS, "Midnight Purple Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.MIDNIGHT_PURPLE_MUD_BRICK_SHINGLES, "Midnight Purple Mud Brick Shingles");
		this.addBlock(BlockRegistry.MIDNIGHT_PURPLE_REED_MAT, "Midnight Purple Reed Mat");
		this.addBlock(BlockRegistry.MIDNIGHT_PURPLE_SAMITE, "Midnight Purple Samite");
		this.addBlock(BlockRegistry.MIDNIGHT_PURPLE_SAMITE_CANVAS_PANEL, "Midnight Purple Samite Canvas Panel");
		this.addBlock(BlockRegistry.MILKWEED, "Milkweed");
		this.addBlock(BlockRegistry.MIMIC_DUNGEON_DOOR_RUNES, "Dungeon Door");
		this.addBlock(BlockRegistry.MIRAGE_BETWEENSTONE_BRICKS, "Betweenstone Bricks");
		this.addBlock(BlockRegistry.MIRE_CORAL, "Mire Coral");
		this.addBlock(BlockRegistry.MIRE_CORAL_BLOCK, "Miral Coral Block");
		this.addBlock(BlockRegistry.MIST_BRIDGE, "Mist Bridge");
		this.addBlock(BlockRegistry.MOB_SPAWNER, "Monster Spawner");
		this.addBlock(BlockRegistry.MORTAR, "Mortar");
		this.addBlock(BlockRegistry.MOSS, "Moss");
		this.addBlock(BlockRegistry.MOSS_BED, "Moss Bed");
		this.addBlock(BlockRegistry.MOSSY_BETWEENSTONE_BRICK_SLAB, "Mossy Betweenstone Brick Slab");
		this.addBlock(BlockRegistry.MOSSY_BETWEENSTONE_BRICK_STAIRS, "Mossy Betweenstone Brick Stairs");
		this.addBlock(BlockRegistry.MOSSY_BETWEENSTONE_BRICK_WALL, "Mossy Betweenstone Brick Wall");
		this.addBlock(BlockRegistry.MOSSY_BETWEENSTONE_BRICKS, "Mossy Betweenstone Bricks");
		this.addBlock(BlockRegistry.MOSSY_BETWEENSTONE_TILES, "Mossy Betweenstone Tiles");
		this.addBlock(BlockRegistry.MOSSY_CHISELED_CRAGROCK, "Mossy Chiseled Cragrock");
		this.addBlock(BlockRegistry.MOSSY_CRAGROCK_BOTTOM, "Mossy Cragrock Bottom");
		this.addBlock(BlockRegistry.MOSSY_CRAGROCK_BRICKS, "Mossy Cragrock Bricks");
		this.addBlock(BlockRegistry.MOSSY_CRAGROCK_TILES, "Mossy Cragrock Tiles");
		this.addBlock(BlockRegistry.MOSSY_CRAGROCK_TOP, "Mossy Cragrock Top");
		this.addBlock(BlockRegistry.MOSSY_LIMESTONE_BRICKS, "Mossy Limestone Bricks");
		this.addBlock(BlockRegistry.MOSSY_SMOOTH_BETWEENSTONE, "Mossy Smooth Betweenstone");
		this.addBlock(BlockRegistry.MOSSY_SMOOTH_BETWEENSTONE_SLAB, "Mossy Smooth Betweenstone Slab");
		this.addBlock(BlockRegistry.MOSSY_SMOOTH_BETWEENSTONE_STAIRS, "Mossy Smooth Betweenstone Stairs");
		this.addBlock(BlockRegistry.MOSSY_SMOOTH_BETWEENSTONE_WALL, "Mossy Smooth Betweenstone Wall");
		this.addBlock(BlockRegistry.MOTH_HOUSE, "Moth House");
		this.addBlock(BlockRegistry.MOTH_INFESTED_WEEDWOOD_BUSH, "Moth Infested Weedwood Bush");
		this.addBlock(BlockRegistry.MUD, "Mud");
		this.addBlock(BlockRegistry.MUD_BRICK_ALCOVE, "Mud Brick Alcove");
		this.addBlock(BlockRegistry.MUD_BRICK_SHINGLE_ROOF, "Mud Brick Shingle Roof");
		this.addBlock(BlockRegistry.MUD_BRICK_SHINGLE_SLAB, "Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.MUD_BRICK_SHINGLE_STAIRS, "Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.MUD_BRICK_SHINGLE_WALL, "Mud Brick Shingle Wall");
		this.addBlock(BlockRegistry.MUD_BRICK_SHINGLES, "Mud Brick Shingles");
		this.addBlock(BlockRegistry.MUD_BRICK_SLAB, "Mud Brick Slab");
		this.addBlock(BlockRegistry.MUD_BRICK_SPIKE_TRAP, "Mud Brick Spike Trap");
		this.addBlock(BlockRegistry.MUD_BRICK_STAIRS, "Mud Brick Stairs");
		this.addBlock(BlockRegistry.MUD_BRICK_WALL, "Mud Brick Wall");
		this.addBlock(BlockRegistry.MUD_BRICKS, "Mud Bricks");
		this.addBlock(BlockRegistry.MUD_ENERGY_BARRIER, "Energy Barrier");
		this.addBlock(BlockRegistry.MUD_FLOWER_POT, "Mud Flower Pot");
		this.addBlock(BlockRegistry.MUD_FLOWER_POT_CANDLE, "Mud Flower Pot Candle");
		this.addBlock(BlockRegistry.MUD_LOOT_POT_1, "Muddy Pot of Chance");
		this.addBlock(BlockRegistry.MUD_LOOT_POT_2, "Muddy Pot of Chance");
		this.addBlock(BlockRegistry.MUD_LOOT_POT_3, "Muddy Pot of Chance");
		this.addBlock(BlockRegistry.MUD_TILES, "Mud Tiles");
		this.addBlock(BlockRegistry.MUD_TILES_SPIKE_TRAP, "Mud Tile Spike Trap");
		this.addBlock(BlockRegistry.NETTLE, "Nettle");
		this.addBlock(BlockRegistry.NIBBLETWIG_BARK, "Nibbletwig Bark");
		this.addBlock(BlockRegistry.NIBBLETWIG_DOOR, "Nibbletwig Door");
		this.addBlock(BlockRegistry.NIBBLETWIG_FENCE, "Nibbletwig Fence");
		this.addBlock(BlockRegistry.NIBBLETWIG_FENCE_GATE, "Nibbletwig Fence Gate");
		this.addBlock(BlockRegistry.NIBBLETWIG_LEAVES, "Nibbletwig Leaves");
		this.addBlock(BlockRegistry.NIBBLETWIG_LOG, "Nibbletwig Log");
		this.addBlock(BlockRegistry.NIBBLETWIG_PLANKS, "Nibbletwig Planks");
		this.addBlock(BlockRegistry.NIBBLETWIG_SAPLING, "Nibbletwig Sapling");
		this.addBlock(BlockRegistry.NIBBLETWIG_SLAB, "Nibbletwig Slab");
		this.addBlock(BlockRegistry.NIBBLETWIG_STAIRS, "Nibbletwig Stairs");
		this.addBlock(BlockRegistry.NIBBLETWIG_TRAPDOOR, "Nibbletwig Trapdoor");
		this.addBlock(BlockRegistry.OCTINE_BLOCK, "Block of Octine");
		this.addBlock(BlockRegistry.OCTINE_ORE, "Octine Ore");
		this.addBlock(BlockRegistry.OFFERING_TABLE, "Offering Table");
		this.addBlock(BlockRegistry.ORANGE_ASPECT_VIAL, "Orange Aspect Vial");
		this.addBlock(BlockRegistry.ORANGE_DENTROTHYST, "Orange Dentrothyst");
		this.addBlock(BlockRegistry.ORANGE_PRESENT, "Orange Present");

		this.addBlock(BlockRegistry.PALE_GRASS, "Pale Grass");
		this.addBlock(BlockRegistry.PAPER_LANTERN_1, "Blank Amate Paper Lantern");
		this.addBlock(BlockRegistry.PAPER_LANTERN_2, "Checkered Amate Paper Lantern");
		this.addBlock(BlockRegistry.PAPER_LANTERN_3, "Framed Amate Paper Lantern");
		this.addBlock(BlockRegistry.PEARL_BLOCK, "Block of Pearls");
		this.addBlock(BlockRegistry.PEAT, "Peat");
		this.addBlock(BlockRegistry.PEWTER_GREY_FILTERED_SILT_GLASS_BLOCK, "Pewter Grey Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.PEWTER_GREY_MUD_BRICK_SHINGLE_SLAB, "Pewter Grey Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.PEWTER_GREY_MUD_BRICK_SHINGLE_STAIRS, "Pewter Grey Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.PEWTER_GREY_MUD_BRICK_SHINGLES, "Pewter Grey Mud Brick Shingles");
		this.addBlock(BlockRegistry.PEWTER_GREY_REED_MAT, "Pewter Grey Reed Mat");
		this.addBlock(BlockRegistry.PEWTER_GREY_SAMITE, "Pewter Grey Samite");
		this.addBlock(BlockRegistry.PEWTER_GREY_SAMITE_CANVAS_PANEL, "Pewter Grey Samite Canvas Panel");
		this.addBlock(BlockRegistry.PHEROMONE_INFUSED_WEEDWOOD_BUSH, "Pheromone Infused Weedwood Bush");
		this.addBlock(BlockRegistry.PHRAGMITES, "Phragmites");
		this.addBlock(BlockRegistry.PICKERELWEED, "Pickerelweed");
		this.addBlock(BlockRegistry.PINK_BAUBLE, "Pink Bauble");
		this.addBlock(BlockRegistry.PINK_PRESENT, "Pink Present");
		this.addBlock(BlockRegistry.PITCHER_PLANT, "Pitcher Plant");
		this.addBlock(BlockRegistry.PITSTONE, "Pitstone");
		this.addBlock(BlockRegistry.PITSTONE_BRICK_SLAB, "Pitstone Brick Slab");
		this.addBlock(BlockRegistry.PITSTONE_BRICK_STAIRS, "Pitstone Brick Stairs");
		this.addBlock(BlockRegistry.PITSTONE_BRICK_WALL, "Pitstone Brick Wall");
		this.addBlock(BlockRegistry.PITSTONE_BRICKS, "Pitstone Bricks");
		this.addBlock(BlockRegistry.PITSTONE_PILLAR, "Pitstone Pillar");
		this.addBlock(BlockRegistry.PITSTONE_SLAB, "Pitstone Slab");
		this.addBlock(BlockRegistry.PITSTONE_STAIRS, "Pitstone Stairs");
		this.addBlock(BlockRegistry.PITSTONE_TILES, "Pitstone Tiles");
		this.addBlock(BlockRegistry.PITSTONE_WALL, "Pitstone Wall");
		this.addBlock(BlockRegistry.POISON_IVY, "Poison Ivy");
		this.addBlock(BlockRegistry.POLISHED_GREEN_DENTROTHYST, "Polished Green Dentrothyst");
		this.addBlock(BlockRegistry.POLISHED_GREEN_DENTROTHYST_PANE, "Polished Green Dentrothyst Pane");
		this.addBlock(BlockRegistry.POLISHED_LIMESTONE, "Polished Limestone");
		this.addBlock(BlockRegistry.POLISHED_LIMESTONE_SLAB, "Polished Limestone Slab");
		this.addBlock(BlockRegistry.POLISHED_LIMESTONE_STAIRS, "Polished Limestone Stairs");
		this.addBlock(BlockRegistry.POLISHED_LIMESTONE_WALL, "Polished Limestone Wall");
		this.addBlock(BlockRegistry.POLISHED_ORANGE_DENTROTHYST, "Polished Orange Dentrothyst");
		this.addBlock(BlockRegistry.POLISHED_ORANGE_DENTROTHYST_PANE, "Polished Orange Dentrothyst Pane");
		this.addBlock(BlockRegistry.PORTAL, "Portal");
		this.addBlock(BlockRegistry.PORTAL_FRAME_BOTTOM, "Portal Frame");
		this.addBlock(BlockRegistry.PORTAL_FRAME_BOTTOM_LEFT, "Portal Frame");
		this.addBlock(BlockRegistry.PORTAL_FRAME_BOTTOM_RIGHT, "Portal Frame");
		this.addBlock(BlockRegistry.PORTAL_FRAME_LEFT, "Portal Frame");
		this.addBlock(BlockRegistry.PORTAL_FRAME_RIGHT, "Portal Frame");
		this.addBlock(BlockRegistry.PORTAL_FRAME_TOP, "Portal Frame");
		this.addBlock(BlockRegistry.PORTAL_FRAME_TOP_LEFT, "Portal Frame");
		this.addBlock(BlockRegistry.PORTAL_FRAME_TOP_RIGHT, "Portal Frame");
		this.addBlock(BlockRegistry.PORTAL_LOG, "Portal Log");
		this.addBlock(BlockRegistry.POSSESSED_BLOCK, "Betweenstone Bricks");
		this.addBlock(BlockRegistry.PUDDLE, "Puddle");
		this.addBlock(BlockRegistry.PUFFSHROOM, "Puffshroom");
		this.addBlock(BlockRegistry.PURIFIED_DUG_SWAMP_DIRT, "Purified Dug Swamp Dirt");
		this.addBlock(BlockRegistry.PURIFIED_DUG_SWAMP_GRASS, "Purified Dug Swamp Grass");
		this.addBlock(BlockRegistry.PURIFIED_SWAMP_DIRT, "Purified Swamp Dirt");
		this.addBlock(BlockRegistry.PURIFIER, "Purifier");
		this.addBlock(BlockRegistry.PURPLE_PRESENT, "Purple Present");
		this.addBlock(BlockRegistry.RAISIN_BLACK_FILTERED_SILT_GLASS_BLOCK, "Raisin Black Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.RAISIN_BLACK_MUD_BRICK_SHINGLE_SLAB, "Raisin Black Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.RAISIN_BLACK_MUD_BRICK_SHINGLE_STAIRS, "Raisin Black Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.RAISIN_BLACK_MUD_BRICK_SHINGLES, "Raisin Black Mud Brick Shingles");
		this.addBlock(BlockRegistry.RAISIN_BLACK_REED_MAT, "Raisin Black Reed Mat");
		this.addBlock(BlockRegistry.RAISIN_BLACK_SAMITE, "Raisin Black Samite");
		this.addBlock(BlockRegistry.RAISIN_BLACK_SAMITE_CANVAS_PANEL, "Raisin Black Samite Canvas Panel");
		this.addBlock(BlockRegistry.RED_BAUBLE, "Red Bauble");
		this.addBlock(BlockRegistry.RED_PRESENT, "Red Present");
		this.addBlock(BlockRegistry.REED_MAT, "Reed Mat");
		this.addBlock(BlockRegistry.REPELLER, "Repeller");
		this.addBlock(BlockRegistry.ROOT, "Root");
		this.addBlock(BlockRegistry.ROOTMAN_SIMULACRUM_1, "Rootman Simulacrum");
		this.addBlock(BlockRegistry.ROOTMAN_SIMULACRUM_2, "Rootman Simulacrum");
		this.addBlock(BlockRegistry.ROOTMAN_SIMULACRUM_3, "Rootman Simulacrum");
		this.addBlock(BlockRegistry.ROPE, "Rope");
		this.addBlock(BlockRegistry.ROTBULB, "Rotbulb");
		this.addBlock(BlockRegistry.ROTTEN_BARK, "Rotten bark");
		this.addBlock(BlockRegistry.ROTTEN_FENCE, "Rotten Fence");
		this.addBlock(BlockRegistry.ROTTEN_FENCE_GATE, "Rotten Fence Gate");
		this.addBlock(BlockRegistry.ROTTEN_DOOR, "Rotten Door");
		this.addBlock(BlockRegistry.ROTTEN_TRAPDOOR, "Rotten Trapdoor");
		this.addBlock(BlockRegistry.ROTTEN_PLANKS, "Rotten Planks");
		this.addBlock(BlockRegistry.ROTTEN_SLAB, "Rotten Slab");
		this.addBlock(BlockRegistry.ROTTEN_STAIRS, "Rotten Stairs");
		this.addBlock(BlockRegistry.ROUNDED_AMATE_PAPER_PANE, "Rounded Amate Paper Pane");
		this.addBlock(BlockRegistry.RUBBER, "Rubber");
		this.addBlock(BlockRegistry.RUBBER_BLOCK, "Block of Rubber");
		this.addBlock(BlockRegistry.RUBBER_LOG, "Rubber Log");
		this.addBlock(BlockRegistry.RUBBER_SAPLING, "Rubber Sapling");
		this.addBlock(BlockRegistry.RUBBER_TREE_DOOR, "Rubber Tree Door");
		this.addBlock(BlockRegistry.RUBBER_TREE_FENCE, "Rubber Tree Fence");
		this.addBlock(BlockRegistry.RUBBER_TREE_FENCE_GATE, "Rubber Tree Fence Gate");
		this.addBlock(BlockRegistry.RUBBER_TREE_LEAVES, "Rubber Tree Leaves");
		this.addBlock(BlockRegistry.RUBBER_TREE_PLANKS, "Rubber Tree Planks");
		this.addBlock(BlockRegistry.RUBBER_TREE_SLAB, "Rubber Tree Slab");
		this.addBlock(BlockRegistry.RUBBER_TREE_STAIRS, "Rubber Tree Stairs");
		this.addBlock(BlockRegistry.RUBBER_TREE_TRAPDOOR, "Rubber Tree Trapdoor");
		this.addBlock(BlockRegistry.SAFFRON_FILTERED_SILT_GLASS_BLOCK, "Saffron Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.SAFFRON_MUD_BRICK_SHINGLE_SLAB, "Saffron Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.SAFFRON_MUD_BRICK_SHINGLE_STAIRS, "Saffron Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.SAFFRON_MUD_BRICK_SHINGLES, "Saffron Mud Brick Shingles");
		this.addBlock(BlockRegistry.SAFFRON_REED_MAT, "Saffron Reed Mat");
		this.addBlock(BlockRegistry.SAFFRON_SAMITE, "Saffron Samite");
		this.addBlock(BlockRegistry.SAFFRON_SAMITE_CANVAS_PANEL, "Saffron Samite Canvas Panel");
		this.addBlock(BlockRegistry.SAP_BARK, "Sap Bark");
		this.addBlock(BlockRegistry.SAP_LEAVES, "Sap Leaves");
		this.addBlock(BlockRegistry.SAP_LOG, "Sap Log");
		this.addBlock(BlockRegistry.SAP_SAPLING, "Sap Sapling");
		this.addBlock(BlockRegistry.SCABYST_BLOCK, "Block of Scabyst");
		this.addBlock(BlockRegistry.SCABYST_BRICK_SLAB, "Scabyst Brick Slab");
		this.addBlock(BlockRegistry.SCABYST_BRICK_STAIRS, "Scabyst Brick Stairs");
		this.addBlock(BlockRegistry.SCABYST_BRICK_WALL, "Scabyst Brick Wall");
		this.addBlock(BlockRegistry.SCABYST_BRICKS, "Scabyst Bricks");
		this.addBlock(BlockRegistry.SCABYST_DOOR, "Scabyst Door");
		this.addBlock(BlockRegistry.SCABYST_ORE, "Scabyst Ore");
		this.addBlock(BlockRegistry.SCABYST_TRAPDOOR, "Scabyst Trapdoor");
		this.addBlock(BlockRegistry.SEEDED_HANGER, "Seeded Hanger");
		this.addBlock(BlockRegistry.SHADOW_GREEN_FILTERED_SILT_GLASS_BLOCK, "Shadow Green Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.SHADOW_GREEN_MUD_BRICK_SHINGLE_SLAB, "Shadow Green Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.SHADOW_GREEN_MUD_BRICK_SHINGLE_STAIRS, "Shadow Green Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.SHADOW_GREEN_MUD_BRICK_SHINGLES, "Shadow Green Mud Brick Shingles");
		this.addBlock(BlockRegistry.SHADOW_GREEN_REED_MAT, "Shadow Green Reed Mat");
		this.addBlock(BlockRegistry.SHADOW_GREEN_SAMITE, "Shadow Green Samite");
		this.addBlock(BlockRegistry.SHADOW_GREEN_SAMITE_CANVAS_PANEL, "Shadow Green Samite Canvas Panel");
		this.addBlock(BlockRegistry.SHADOW_WALKER, "Shadow Walker");
		this.addBlock(BlockRegistry.SHELF_FUNGUS, "Shelf Fungus");
		this.addBlock(BlockRegistry.SHOOTS, "Shoots");
		this.addBlock(BlockRegistry.SHORT_SWAMP_GRASS, "Short Swamp Grass");
		this.addBlock(BlockRegistry.SILK_COCOONED_WEEDWOOD_BUSH, "Silk Cocooned Weedwood Bush");
		this.addBlock(BlockRegistry.SILT, "Silt");
		this.addBlock(BlockRegistry.SILT_GLASS, "Silt Glass");
		this.addBlock(BlockRegistry.SILT_GLASS_JAR, "Silt Glass Jar");
		this.addBlock(BlockRegistry.SILT_GLASS_LANTERN, "Silt Glass Lantern");
		this.addBlock(BlockRegistry.SILT_GLASS_PANE, "Silt Glass Pane");
		this.addBlock(BlockRegistry.SLIMY_BONE_BLOCK, "Block of Slimy Bone");
		this.addBlock(BlockRegistry.SLIMY_BONE_ORE, "Slimy Bone Ore");
		this.addBlock(BlockRegistry.SLIMY_DIRT, "Slimy Dirt");
		this.addBlock(BlockRegistry.SLIMY_GRASS, "Slimy Grass");
		this.addBlock(BlockRegistry.SLUDGE, "Sludge");
		this.addBlock(BlockRegistry.SLUDGECREEP, "Sludgecreep");
		this.addBlock(BlockRegistry.SLUDGY_CARVED_MUD_BRICK_EDGE_1, "Sludgy Carved Mud Brick Edge 1");
		this.addBlock(BlockRegistry.SLUDGY_CARVED_MUD_BRICK_EDGE_2, "Sludgy Carved Mud Brick Edge 2");
		this.addBlock(BlockRegistry.SLUDGY_CARVED_MUD_BRICK_EDGE_3, "Sludgy Carved Mud Brick Edge 3");
		this.addBlock(BlockRegistry.SLUDGY_CARVED_MUD_BRICK_EDGE_4, "Sludgy Carved Mud Brick Edge 4");
		this.addBlock(BlockRegistry.SLUDGY_CARVED_MUD_BRICKS_1, "Sludgy Carved Mud Bricks 1");
		this.addBlock(BlockRegistry.SLUDGY_CARVED_MUD_BRICKS_2, "Sludgy Carved Mud Bricks 2");
		this.addBlock(BlockRegistry.SLUDGY_CARVED_MUD_BRICKS_3, "Sludgy Carved Mud Bricks 3");
		this.addBlock(BlockRegistry.SLUDGY_CARVED_MUD_BRICKS_4, "Sludgy Carved Mud Bricks 4");
		this.addBlock(BlockRegistry.SLUDGY_DIRT, "Sludgy Dirt");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICK_SLAB_1, "Sludgy Mud Brick Slab 1");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICK_SLAB_2, "Sludgy Mud Brick Slab 2");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICK_SLAB_3, "Sludgy Mud Brick Slab 3");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICK_SLAB_4, "Sludgy Mud Brick Slab 4");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICK_STAIRS_1, "Sludgy Mud Brick Stairs 1");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICK_STAIRS_2, "Sludgy Mud Brick Stairs 2");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICK_STAIRS_3, "Sludgy Mud Brick Stairs 3");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICK_STAIRS_4, "Sludgy Mud Brick Stairs 4");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICKS_1, "Sludgy Mud Bricks 1");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICKS_2, "Sludgy Mud Bricks 2");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICKS_3, "Sludgy Mud Bricks 3");
		this.addBlock(BlockRegistry.SLUDGY_MUD_BRICKS_4, "Sludgy Mud Bricks 4");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_1, "Sludgy Worm Pillar 1");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_2, "Sludgy Worm Pillar 2");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_3, "Sludgy Worm Pillar 3");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_4, "Sludgy Worm Pillar 4");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_5, "Sludgy Worm Pillar 5");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_TOP_1, "Sludgy Worm Pillar Top 1");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_TOP_2, "Sludgy Worm Pillar Top 2");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_TOP_3, "Sludgy Worm Pillar Top 3");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_TOP_4, "Sludgy Worm Pillar Top 4");
		this.addBlock(BlockRegistry.SLUDGY_WORM_PILLAR_TOP_5, "Sludgy Worm Pillar Top 5");
		this.addBlock(BlockRegistry.SMOKING_RACK, "Smoking Rack");
		this.addBlock(BlockRegistry.SMOOTH_BETWEENSTONE, "Smooth Betweenstone");
		this.addBlock(BlockRegistry.SMOOTH_BETWEENSTONE_SLAB, "Smooth Betweenstone Slab");
		this.addBlock(BlockRegistry.SMOOTH_BETWEENSTONE_STAIRS, "Smooth Betweenstone Stairs");
		this.addBlock(BlockRegistry.SMOOTH_BETWEENSTONE_WALL, "Smooth Betweenstone Wall");
		this.addBlock(BlockRegistry.SMOOTH_CRAGROCK, "Smooth Cragrock");
		this.addBlock(BlockRegistry.SMOOTH_CRAGROCK_SLAB, "Smooth Cragrock Slab");
		this.addBlock(BlockRegistry.SMOOTH_CRAGROCK_STAIRS, "Smooth Cragrock Stairs");
		this.addBlock(BlockRegistry.SMOOTH_CRAGROCK_WALL, "Smooth Cragrock Wall");
		this.addBlock(BlockRegistry.SMOOTH_PITSTONE, "Smooth Pitstone");
		this.addBlock(BlockRegistry.SMOOTH_PITSTONE_SLAB, "Smooth Pitstone Slab");
		this.addBlock(BlockRegistry.SMOOTH_PITSTONE_STAIRS, "Smooth Pitstone Stairs");
		this.addBlock(BlockRegistry.SMOOTH_PITSTONE_WALL, "Smooth Pitstone Wall");
		this.addBlock(BlockRegistry.SMOULDERING_PEAT, "Smouldering Peat");
		this.addBlock(BlockRegistry.SNOW, "Snow");
		this.addBlock(BlockRegistry.SOFT_RUSH, "Soft Rush");
		this.addBlock(BlockRegistry.SOLID_TAR, "Solid Tar");
		this.addBlock(BlockRegistry.SOLID_TAR_SLAB, "Solid Tar Slab");
		this.addBlock(BlockRegistry.SOLID_TAR_STAIRS, "Solid Tar Stairs");
		this.addBlock(BlockRegistry.SOLID_TAR_WALL, "Solid Tar Wall");
		this.addBlock(BlockRegistry.SPIKE_TRAP, "Spike Trap");
		this.addBlock(BlockRegistry.SPIRIT_TREE_BARK, "Spirit Tree Bark");
		this.addBlock(BlockRegistry.SPIRIT_TREE_LOG, "Spirit Tree Log");
		this.addBlock(BlockRegistry.SPREADING_ROTTEN_BARK, "Rotten Bark");
		this.addBlock(BlockRegistry.SPREADING_SLUDGY_DIRT, "Sludgy Dirt");
		this.addBlock(BlockRegistry.SQUARED_AMATE_PAPER_PANE, "Squared Amate Paper Pane");
		this.addBlock(BlockRegistry.STAGNANT_WATER, "Stagnant Water");
		this.addBlock(BlockRegistry.STALACTITE, "Stalactite");
		this.addBlock(BlockRegistry.STEEPING_POT, "Steeping Pot");
		this.addBlock(BlockRegistry.STICK_NESTING_BLOCK, "Nesting Block");
		this.addBlock(BlockRegistry.STRING_ROOTS, "String Roots");
		this.addBlock(BlockRegistry.STRING_ROOTS_PLANT, "String Roots Plant");
		this.addBlock(BlockRegistry.SULFUR_BLOCK, "Block of Sulfur");
		this.addBlock(BlockRegistry.SULFUR_FURNACE, "Sulfur Furnace");
		this.addBlock(BlockRegistry.SULFUR_ORE, "Sulfur Ore");
		this.addBlock(BlockRegistry.SULFUR_TORCH, "Sulfur Torch");
		this.addBlock(BlockRegistry.SUNDEW, "Sundew");
		this.addBlock(BlockRegistry.SUSHI_GREEN_FILTERED_SILT_GLASS_BLOCK, "Sushi Green Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.SUSHI_GREEN_MUD_BRICK_SHINGLE_SLAB, "Sushi Green Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.SUSHI_GREEN_MUD_BRICK_SHINGLE_STAIRS, "Sushi Green Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.SUSHI_GREEN_MUD_BRICK_SHINGLES, "Sushi Green Mud Brick Shingles");
		this.addBlock(BlockRegistry.SUSHI_GREEN_REED_MAT, "Sushi Green Reed Mat");
		this.addBlock(BlockRegistry.SUSHI_GREEN_SAMITE, "Sushi Green Samite");
		this.addBlock(BlockRegistry.SUSHI_GREEN_SAMITE_CANVAS_PANEL, "Sushi Green Samite Canvas Panel");
		this.addBlock(BlockRegistry.SWAMP_DIRT, "Swamp Dirt");
		this.addBlock(BlockRegistry.SWAMP_GRASS, "Swamp Grass");
		this.addBlock(BlockRegistry.SWAMP_KELP, "Swamp Kelp");
		this.addBlock(BlockRegistry.SWAMP_KELP_PLANT, "Swamp Kelp Plant");
		this.addBlock(BlockRegistry.SWAMP_PLANT, "Swamp Plant");
		this.addBlock(BlockRegistry.SWAMP_REED, "Swamp Reed");
		this.addBlock(BlockRegistry.SWAMP_WATER, "Swamp Water");
		this.addBlock(BlockRegistry.SYRMORITE_BARREL, "Syrmorite Barrel");
		this.addBlock(BlockRegistry.SYRMORITE_BLOCK, "Block of Syrmorite");
		this.addBlock(BlockRegistry.SYRMORITE_DOOR, "Syrmorite Door");
		this.addBlock(BlockRegistry.SYRMORITE_HOPPER, "Syrmorite Hopper");
		this.addBlock(BlockRegistry.SYRMORITE_ORE, "Syrmorite Ore");
		this.addBlock(BlockRegistry.SYRMORITE_PRESSURE_PLATE, "Syrmorite Pressure Plate");
		this.addBlock(BlockRegistry.SYRMORITE_RUBBER_TAP, "Syrmorite Rubber Tap");
		this.addBlock(BlockRegistry.SYRMORITE_TRAPDOOR, "Syrmorite Trapdoor");
		this.addBlock(BlockRegistry.TALL_CATTAIL, "Tall Cattail");
		this.addBlock(BlockRegistry.TALL_SLUDGECREEP, "Tall Sludgecreep");
		this.addBlock(BlockRegistry.TALL_SWAMP_GRASS, "Tall Swamp Grass");
		this.addBlock(BlockRegistry.TAR, "Tar");
		this.addBlock(BlockRegistry.TAR_LOOT_POT_1, "Tarred Pot of Chance");
		this.addBlock(BlockRegistry.TAR_LOOT_POT_2, "Tarred Pot of Chance");
		this.addBlock(BlockRegistry.TAR_LOOT_POT_3, "Tarred Pot of Chance");
		this.addBlock(BlockRegistry.TARRED_HEARTHGROVE_BARK, "Tarred Hearthgrove Bark");
		this.addBlock(BlockRegistry.TARRED_HEARTHGROVE_LOG, "Tarred Hearthgrove Log");
		this.addBlock(BlockRegistry.TEMPLE_BRICK_SLAB, "Temple Brick Slab");
		this.addBlock(BlockRegistry.TEMPLE_BRICK_STAIRS, "Temple Brick Stairs");
		this.addBlock(BlockRegistry.TEMPLE_BRICK_WALL, "Temple Brick Wall");
		this.addBlock(BlockRegistry.TEMPLE_BRICKS, "Temple Bricks");
		this.addBlock(BlockRegistry.TEMPLE_PILLAR, "Temple Pillar");
		this.addBlock(BlockRegistry.THATCH, "Thatch");
		this.addBlock(BlockRegistry.THATCH_ROOF, "Thatch Roof");
		this.addBlock(BlockRegistry.THATCH_SLAB, "Thatch Slab");
		this.addBlock(BlockRegistry.THORNS, "Thorns");
		this.addBlock(BlockRegistry.TOP_SPIRIT_TREE_LEAVES, "Upper Spirit Tree Leaves");
		this.addBlock(BlockRegistry.TREATED_GIANT_ROOT_DOOR, "Treated Giant Root Door");
		this.addBlock(BlockRegistry.TREATED_GIANT_ROOT_FENCE, "Treated Giant Root Fence");
		this.addBlock(BlockRegistry.TREATED_GIANT_ROOT_FENCE_GATE, "Treated Giant Root Fence Gate");
		this.addBlock(BlockRegistry.TREATED_GIANT_ROOT_PLANKS, "Treated Giant Root Planks");
		this.addBlock(BlockRegistry.TREATED_GIANT_ROOT_SLAB, "Treated Giant Root Slab");
		this.addBlock(BlockRegistry.TREATED_GIANT_ROOT_STAIRS, "Treated Giant Root Stairs");
		this.addBlock(BlockRegistry.TREATED_GIANT_ROOT_TRAPDOOR, "Treated Giant Root Trapdoor");
		this.addBlock(BlockRegistry.TREATED_HEARTHGROVE_DOOR, "Treated Hearthgrove Door");
		this.addBlock(BlockRegistry.TREATED_HEARTHGROVE_FENCE, "Treated Hearthgrove Fence");
		this.addBlock(BlockRegistry.TREATED_HEARTHGROVE_FENCE_GATE, "Treated Hearthgrove Fence Gate");
		this.addBlock(BlockRegistry.TREATED_HEARTHGROVE_PLANKS, "Treated Hearthgrove Planks");
		this.addBlock(BlockRegistry.TREATED_HEARTHGROVE_SLAB, "Treated Hearthgrove Slab");
		this.addBlock(BlockRegistry.TREATED_HEARTHGROVE_STAIRS, "Treated Hearthgrove Stairs");
		this.addBlock(BlockRegistry.TREATED_HEARTHGROVE_TRAPDOOR, "Treated Hearthgrove Trapdoor");
		this.addBlock(BlockRegistry.TREATED_NIBBLETWIG_DOOR, "Treated Nibbletwig Door");
		this.addBlock(BlockRegistry.TREATED_NIBBLETWIG_FENCE, "Treated Nibbletwig Fence");
		this.addBlock(BlockRegistry.TREATED_NIBBLETWIG_FENCE_GATE, "Treated Nibbletwig Fence Gate");
		this.addBlock(BlockRegistry.TREATED_NIBBLETWIG_PLANKS, "Treated Nibbletwig Planks");
		this.addBlock(BlockRegistry.TREATED_NIBBLETWIG_SLAB, "Treated Nibbletwig Slab");
		this.addBlock(BlockRegistry.TREATED_NIBBLETWIG_STAIRS, "Treated Nibbletwig Stairs");
		this.addBlock(BlockRegistry.TREATED_NIBBLETWIG_TRAPDOOR, "Treated Nibbletwig Trapdoor");
		this.addBlock(BlockRegistry.TREATED_ROTTEN_FENCE, "Treated Rotten Fence");
		this.addBlock(BlockRegistry.TREATED_ROTTEN_FENCE_GATE, "Treated Rotten Fence Gate");
		this.addBlock(BlockRegistry.TREATED_ROTTEN_DOOR, "Treated Rotten Door");
		this.addBlock(BlockRegistry.TREATED_ROTTEN_TRAPDOOR, "Treated Rotten Trapdoor");
		this.addBlock(BlockRegistry.TREATED_ROTTEN_PLANKS, "Treated Rotten Planks");
		this.addBlock(BlockRegistry.TREATED_ROTTEN_SLAB, "Treated Rotten Slab");
		this.addBlock(BlockRegistry.TREATED_ROTTEN_STAIRS, "Treated Rotten Stairs");
		this.addBlock(BlockRegistry.TREATED_RUBBER_TREE_DOOR, "Treated Rubber Tree Door");
		this.addBlock(BlockRegistry.TREATED_RUBBER_TREE_FENCE, "Treated Rubber Tree Fence");
		this.addBlock(BlockRegistry.TREATED_RUBBER_TREE_FENCE_GATE, "Treated Rubber Tree Fence Gate");
		this.addBlock(BlockRegistry.TREATED_RUBBER_TREE_PLANKS, "Treated Rubber Tree Planks");
		this.addBlock(BlockRegistry.TREATED_RUBBER_TREE_SLAB, "Treated Rubber Tree Slab");
		this.addBlock(BlockRegistry.TREATED_RUBBER_TREE_STAIRS, "Treated Rubber Tree Stairs");
		this.addBlock(BlockRegistry.TREATED_RUBBER_TREE_TRAPDOOR, "Treated Rubber Tree Trapdoor");
		this.addBlock(BlockRegistry.TREATED_WEEDWOOD_DOOR, "Treated Weedwood Door");
		this.addBlock(BlockRegistry.TREATED_WEEDWOOD_FENCE, "Treated Weedwood Fence");
		this.addBlock(BlockRegistry.TREATED_WEEDWOOD_FENCE_GATE, "Treated Weedwood Fence Gate");
		this.addBlock(BlockRegistry.TREATED_WEEDWOOD_PLANKS, "Treated Weedwood Planks");
		this.addBlock(BlockRegistry.TREATED_WEEDWOOD_SLAB, "Treated Weedwood Slab");
		this.addBlock(BlockRegistry.TREATED_WEEDWOOD_STAIRS, "Treated Weedwood Stairs");
		this.addBlock(BlockRegistry.TREATED_WEEDWOOD_TRAPDOOR, "Treated Weedwood Trapdoor");
		this.addBlock(BlockRegistry.VALONITE_BLOCK, "Block of Valonite");
		this.addBlock(BlockRegistry.VALONITE_ORE, "Valonite Ore");
		this.addBlock(BlockRegistry.VENUS_FLY_TRAP, "Venus Fly Trap");
		this.addBlock(BlockRegistry.VIVID_TANGERINE_FILTERED_SILT_GLASS_BLOCK, "Vivid Tangerine Filtered Silt Glass Block");
		this.addBlock(BlockRegistry.VIVID_TANGERINE_MUD_BRICK_SHINGLE_SLAB, "Vivid Tangerine Mud Brick Shingle Slab");
		this.addBlock(BlockRegistry.VIVID_TANGERINE_MUD_BRICK_SHINGLE_STAIRS, "Vivid Tangerine Mud Brick Shingle Stairs");
		this.addBlock(BlockRegistry.VIVID_TANGERINE_MUD_BRICK_SHINGLES, "Vivid Tangerine Mud Brick Shingles");
		this.addBlock(BlockRegistry.VIVID_TANGERINE_REED_MAT, "Vivid Tangerine Reed Mat");
		this.addBlock(BlockRegistry.VIVID_TANGERINE_SAMITE, "Vivid Tangerine Samite");
		this.addBlock(BlockRegistry.VIVID_TANGERINE_SAMITE_CANVAS_PANEL, "Vivid Tangerine Samite Canvas Panel");
		this.addBlock(BlockRegistry.VOLARPAD, "Volarpad");
		this.addBlock(BlockRegistry.WALKWAY, "Weedwood Walkway");
		this.addBlock(BlockRegistry.WATER_FILTER, "Water Filter");
		this.addBlock(BlockRegistry.WATER_WEEDS, "Water Weeds");
		this.addBlock(BlockRegistry.WAYSTONE, "Menhir");
		this.addBlock(BlockRegistry.WEAK_BETWEENSTONE_TILES, "Weak Betweenstone Tiles");
		this.addBlock(BlockRegistry.WEAK_MOSSY_BETWEENSTONE_TILES, "Weak Mossy Betweenstone Tiles");
		this.addBlock(BlockRegistry.WEAK_POLISHED_LIMESTONE, "Weak Polished Limestone");
		this.addBlock(BlockRegistry.WEAK_SMOOTH_CRAGROCK, "Weak Smooth Cragrock");
		this.addBlock(BlockRegistry.WEEDWOOD, "Weedwood");
		this.addBlock(BlockRegistry.WEEDWOOD_BARK, "Weedwood Bark");
		this.addBlock(BlockRegistry.WEEDWOOD_BARREL, "Weedwood Barrel");
		this.addBlock(BlockRegistry.WEEDWOOD_BUSH, "Weedwood Bush");
		this.addBlock(BlockRegistry.WEEDWOOD_BUTTON, "Weedwood Button");
		this.addBlock(BlockRegistry.WEEDWOOD_CRAFTING_TABLE, "Weedwood Crafting Table");
		this.addBlock(BlockRegistry.WEEDWOOD_DOOR, "Weedwood Door");
		this.addBlock(BlockRegistry.WEEDWOOD_FENCE, "Weedwood Fence");
		this.addBlock(BlockRegistry.WEEDWOOD_FENCE_GATE, "Weedwood Fence Gate");
		this.addBlock(BlockRegistry.WEEDWOOD_JUKEBOX, "Weedwood Jukebox");
		this.addBlock(BlockRegistry.WEEDWOOD_LADDER, "Weedwood Ladder");
		this.addBlock(BlockRegistry.WEEDWOOD_LEVER, "Weedwood Lever");
		this.addBlock(BlockRegistry.WEEDWOOD_LOG, "Weedwood Log");
		this.addBlock(BlockRegistry.WEEDWOOD_LOG_FENCE, "Weedwood Log Fence");
		this.addBlock(BlockRegistry.WEEDWOOD_LOG_FENCE_GATE, "Weedwood Log Fence Gate");
		this.addBlock(BlockRegistry.WEEDWOOD_PLANKS, "Weedwood Planks");
		this.addBlock(BlockRegistry.WEEDWOOD_PRESSURE_PLATE, "Weedwood Pressure Plate");
		this.addBlock(BlockRegistry.WEEDWOOD_RUBBER_TAP, "Weedwood Rubber Tap");
		this.addBlock(BlockRegistry.WEEDWOOD_SAPLING, "Weedwood Sapling");
		this.addBlock(BlockRegistry.WEEDWOOD_SIGN, "Weedwood Sign");
		this.addBlock(BlockRegistry.WEEDWOOD_SLAB, "Weedwood Slab");
		this.addBlock(BlockRegistry.WEEDWOOD_STAIRS, "Weedwood Stairs");
		this.addBlock(BlockRegistry.WEEDWOOD_TRAPDOOR, "Weedwood Trapdoor");
		this.addBlock(BlockRegistry.WEEPING_BLUE, "Weeping Blue");
		this.addBlock(BlockRegistry.WHITE_PRESENT, "White Present");
		this.addBlock(BlockRegistry.WIND_CHIME, "Wind Chime");
		this.addBlock(BlockRegistry.WISP, "Wisp");
		this.addBlock(BlockRegistry.WOODEN_SUPPORT_BEAM_1, "Rotten Support Beam");
		this.addBlock(BlockRegistry.WOODEN_SUPPORT_BEAM_2, "Rotten Support Beam");
		this.addBlock(BlockRegistry.WOODEN_SUPPORT_BEAM_3, "Rotten Support Beam");
		this.addBlock(BlockRegistry.WORM_PILLAR, "Worm Pillar");
		this.addBlock(BlockRegistry.WORM_PILLAR_TOP, "Worm Pillar Top");
		this.addBlock(BlockRegistry.YELLOW_BAUBLE, "Yellow Bauble");
		this.addBlock(BlockRegistry.YELLOW_PRESENT, "Yellow Present");

		this.add("block.thebetweenlands.dungeon_door_runes.locked", "Dungeon door code set!");
		this.add("block.thebetweenlands.good_fuel", "This dense log is excellent as fuel.");
		this.add("block.thebetweenlands.tarrable", "Can be tarred");
		this.add("block.thebetweenlands.mist", "This plant can only grow in Sludgeon mist.");

		this.add("block.thebetweenlands.fog", "Fog");
		this.add("block.thebetweenlands.shallowbreath", "Shallowbreath");
		this.add("block.thebetweenlands.dye", "Dye");
		this.add("block.thebetweenlands.brew", "Drinkable Brew");
		this.add("block.thebetweenlands.clean_water", "Clean Water");
		this.add("block.thebetweenlands.fish_oil", "Fish Oil");

		this.addItem(ItemRegistry.CRIMSON_SNAIL_SHELL, "Crimson Snail Shell");
		this.addItem(ItemRegistry.OCHRE_SNAIL_SHELL, "Ochre Snail Shell");
		this.addItem(ItemRegistry.COMPOST, "Compost");
		this.addItem(ItemRegistry.DRAGONFLY_WING, "Dragonfly Wing");
		this.addItemWithDesc(ItemRegistry.LURKER_SKIN, "Lurker Skin", "Tough and grounded.");
		this.addItem(ItemRegistry.DRIED_SWAMP_REED, "Dried Swamp Reed");
		this.addItem(ItemRegistry.REED_ROPE, "Reed Rope");
		this.addItem(ItemRegistry.MUD_BRICK, "Mud Brick");
		this.addItem(ItemRegistry.SYRMORITE_INGOT, "Syrmorite Ingot");
		this.addItem(ItemRegistry.DRY_BARK, "Dry Bark");
		this.addItem(ItemRegistry.SLIMY_BONE, "Slimy Bone");
		this.addItem(ItemRegistry.SNAPPER_ROOT, "Snapper Root");
		this.addItem(ItemRegistry.STALKER_EYE, "Stalker Eye");
		this.addItem(ItemRegistry.SULFUR, "Sulfur");
		this.addItem(ItemRegistry.VALONITE_SHARD, "Valonite Shard");
		this.addItem(ItemRegistry.WEEDWOOD_STICK, "Weedwood Stick");
		this.addItem(ItemRegistry.ANGLER_TOOTH, "Angler Tooth");
		this.addItem(ItemRegistry.WEEDWOOD_BOWL, "Weedwood Bowl");
		this.addItem(ItemRegistry.RUBBER_BALL, "Rubber Ball");
		this.addItem(ItemRegistry.TAR_BEAST_HEART, "Tar Beast Heart");
		this.addItem(ItemRegistry.ANIMATED_TAR_BEAST_HEART, "Animated Tar Beast Heart");
		this.addItem(ItemRegistry.TAR_DRIP, "Tar Drip");
		this.addItem(ItemRegistry.LIMESTONE_FLUX, "Limestone Flux");
		this.addItem(ItemRegistry.INANIMATE_TARMINION, "Inanimate Tarminion");
		this.addItem(ItemRegistry.POISON_GLAND, "Poison Gland");
		this.addItem(ItemRegistry.AMATE_PAPER, "Amate Paper");
		this.addItem(ItemRegistry.SHOCKWAVE_SWORD_PIECE_1, "Shockwave Sword Piece");
		this.addItem(ItemRegistry.SHOCKWAVE_SWORD_PIECE_2, "Shockwave Sword Piece");
		this.addItem(ItemRegistry.SHOCKWAVE_SWORD_PIECE_3, "Shockwave Sword Piece");
		this.addItem(ItemRegistry.SHOCKWAVE_SWORD_PIECE_4, "Shockwave Sword Piece");
		this.addItem(ItemRegistry.AMULET_SOCKET, "Amulet Socket");
		this.addItem(ItemRegistry.SCABYST, "Scabyst");
		this.addItem(ItemRegistry.ITEM_SCROLL, "Item Scroll");
		this.addItem(ItemRegistry.SYRMORITE_NUGGET, "Syrmorite Nugget");
		this.addItem(ItemRegistry.OCTINE_NUGGET, "Octine Nugget");
		this.addItem(ItemRegistry.VALONITE_SPLINTER, "Valonite Splinter");
		this.addItem(ItemRegistry.CREMAINS, "Cremains");
		this.addItem(ItemRegistry.UNDYING_EMBERS, "Undying Embers");
		this.addItem(ItemRegistry.INANIMATE_ANGRY_PEBBLE, "Inanimate Angry Pebble");
		this.addItem(ItemRegistry.ANCIENT_REMNANT, "Ancient Remnant");
		this.addItem(ItemRegistry.LOOT_SCRAPS, "Loot Scraps");
		this.addItem(ItemRegistry.FABRICATED_SCROLL, "Fabricated Scroll");
		this.addItemWithDesc(ItemRegistry.ANADIA_SWIM_BLADDER, "Anadia Swim Bladder", "Keeps the fish from sinking... and floating.");
		this.addItemWithDesc(ItemRegistry.ANADIA_EYE, "Anadia Eye", "Made for aquatic sight.");
		this.addItemWithDesc(ItemRegistry.ANADIA_GILLS, "Anadia Gills", "Fish don't hold their breath.");
		this.addItemWithDesc(ItemRegistry.ANADIA_SCALES, "Anadia Scales", "Forms a protective layer.");
		this.addItemWithDesc(ItemRegistry.ANADIA_BONES, "Anadia Bones", "Thin, but resilient.");
		this.addItem(ItemRegistry.ANADIA_REMAINS, "Anadia Remains");
		this.addItemWithDesc(ItemRegistry.ANADIA_FINS, "Anadia Fins", "They glide through the water like wings through air.");
		this.addItemWithDesc(ItemRegistry.SNOT, "Snot", "Seems to barely have drag in water.");
		this.addItemWithDesc(ItemRegistry.URCHIN_SPIKE, "Urchin Spike", "Offense as defense.");
		this.addItem(ItemRegistry.FISHING_FLOAT_AND_HOOK, "Fishing Float and Hook");
		this.addItem(ItemRegistry.OLMLETTE_MIXTURE, "Olmlette Mixture");
		this.addItem(ItemRegistry.SILK_COCOON, "Silk Cocoon");
		this.addItem(ItemRegistry.SILK_THREAD, "Silk Thread");
		this.addItem(ItemRegistry.DIRTY_SILK_BUNDLE, "Dirty Silk Bundle");
		this.addItem(ItemRegistry.PHEROMONE_THORAXES, "Clutch of Pheromone Thoraxes");
		this.addItem(ItemRegistry.SWAMP_TALISMAN, "Swamp Talisman");
		this.addItem(ItemRegistry.SWAMP_TALISMAN_PIECE_1, "Swamp Talisman Piece");
		this.addItem(ItemRegistry.SWAMP_TALISMAN_PIECE_2, "Swamp Talisman Piece");
		this.addItem(ItemRegistry.SWAMP_TALISMAN_PIECE_3, "Swamp Talisman Piece");
		this.addItem(ItemRegistry.SWAMP_TALISMAN_PIECE_4, "Swamp Talisman Piece");
		this.addItem(ItemRegistry.WEEDWOOD_ROWBOAT, "Weedwood Rowboat");
		this.addItem(ItemRegistry.ORANGE_DENTROTHYST_SHARD, "Orange Dentrothyst Shard");
		this.addItem(ItemRegistry.GREEN_DENTROTHYST_SHARD, "Green Dentrothyst Shard");
		this.addItem(ItemRegistry.FISH_BAIT, "Fish Bait");
		this.addItemWithDesc(ItemRegistry.FUMIGANT, "Fumigant", "Removes the Stench of Rot on a Player");
		this.addItem(ItemRegistry.SAP_BALL, "Ball of Sap");
		this.addItem(ItemRegistry.MIRE_SNAIL_EGG, "Mire Snail Egg");
		this.addItem(ItemRegistry.COOKED_MIRE_SNAIL_EGG, "Cooked Mire Snail Egg");
		this.addItem(ItemRegistry.RAW_FROG_LEGS, "Raw Frog's Leg");
		this.addItem(ItemRegistry.COOKED_FROG_LEGS, "Fried Frog's Leg");
		this.addItem(ItemRegistry.RAW_SNAIL_FLESH, "Raw Snail Flesh");
		this.addItem(ItemRegistry.COOKED_SNAIL_FLESH, "Seared Snail Flesh");
		this.addItem(ItemRegistry.REED_DONUT, "Reed Donut");
		this.addItem(ItemRegistry.JAM_DONUT, "Jam Donut");
		this.addItem(ItemRegistry.GERTS_DONUT, "Gert's Donut");
		this.addItem(ItemRegistry.PUFFSHROOM_TENDRIL, "Puffshroom Tendril");
		this.addItem(ItemRegistry.KRAKEN_TENTACLE, "Kraken Tentacle");
		this.addItem(ItemRegistry.KRAKEN_CALAMARI, "Kraken Calamari");
		this.addItem(ItemRegistry.MIDDLE_FRUIT, "White Pear");
		this.addItem(ItemRegistry.MINCE_PIE, "Mince Pie");
		this.addItem(ItemRegistry.CHRISTMAS_PUDDING, "Christmas Pudding");
		this.addItem(ItemRegistry.CANDY_CANE, "Candy Cane");
		this.addItem(ItemRegistry.WEEPING_BLUE_PETAL, "Weeping Blue Petal");
		this.addItem(ItemRegistry.WIGHT_HEART, "Wight Heart");
		this.addItem(ItemRegistry.YELLOW_DOTTED_FUNGUS, "Yellow Dotted Fungus");
		this.addItem(ItemRegistry.SILT_CRAB_CLAW, "Crab Claw");
		this.addItem(ItemRegistry.CRAB_STICK, "Crabstick");
		this.addItem(ItemRegistry.SLUDGE_JELLO, "Sludge Jello");
		this.addItem(ItemRegistry.MIDDLE_FRUIT_JELLO, "White Pear Jello");
		this.addItem(ItemRegistry.SAP_JELLO, "Sap Jello");
		this.addItem(ItemRegistry.GREEN_MARSHMALLOW, "Green Marshmallow");
		this.addItem(ItemRegistry.PINK_MARSHMALLOW, "Pink Marshmallow");
		this.addItem(ItemRegistry.FLATHEAD_MUSHROOM, "Flathead Mushroom");
		this.addItem(ItemRegistry.BLACK_HAT_MUSHROOM, "Black Hat Mushroom");
		this.addItem(ItemRegistry.BULB_CAPPED_MUSHROOM, "Bulb-Capped Mushroom");
		this.addItem(ItemRegistry.FRIED_SWAMP_KELP, "Fried Swamp Kelp");
		this.addItemWithDesc(ItemRegistry.FORBIDDEN_FIG, "Forbidden Fig", "Looks tempting...");
		this.addItem(ItemRegistry.BLUE_CANDY, "Blue Candy");
		this.addItem(ItemRegistry.RED_CANDY, "Red Candy");
		this.addItem(ItemRegistry.YELLOW_CANDY, "Yellow Candy");
		this.addItem(ItemRegistry.CHIROMAW_WING, "Chiromaw Wing");
		this.add("item.thebetweenlands.chiromaw_wing.eat", "Anything will taste better after eating this...");
		this.add("item.thebetweenlands.chiromaw_wing.dont_eat", "I probably shouldn't eat this anymore...");
		this.addItem(ItemRegistry.TANGLED_ROOT, "Tangled Root");
		this.addItem(ItemRegistry.MIRE_SCRAMBLE, "Mire Scramble");
		this.addItem(ItemRegistry.WEEPING_BLUE_PETAL_SALAD, "Weeping Blue Petal Salad");
		this.addItem(ItemRegistry.NIBBLESTICK, "Nibblestick");
		this.addItem(ItemRegistry.SPIRIT_FRUIT, "Spirit Fruit");
		this.addItem(ItemRegistry.SUSHI, "Sushi");
		this.addItemWithDesc(ItemRegistry.ROCK_SNOT_PEARL, "Rocksnot Pearl", "Grants 10 experience when consumed");
		this.addItemWithDesc(ItemRegistry.PEARLED_PEAR, "Pearled Pear", "Grants 80 experience when consumed");
		this.addItem(ItemRegistry.RAW_ANADIA_MEAT, "Raw Anadia Meat");
		this.addItem(ItemRegistry.COOKED_ANADIA_MEAT, "Cooked Anadia Meat");
		this.addItem(ItemRegistry.SMOKED_ANADIA_MEAT, "Smoked Anadia Meat");
		this.addItem(ItemRegistry.BARNACLE, "Barnacle Flesh");
		this.addItem(ItemRegistry.COOKED_BARNACLE, "Cooked Barnacle Flesh");
		this.addItem(ItemRegistry.SMOKED_BARNACLE, "Smoked Barnacle Flesh");
		this.addItem(ItemRegistry.SMOKED_CRAB_STICK, "Smoked Crabstick");
		this.addItem(ItemRegistry.SMOKED_FROG_LEGS, "Smoked Frog's Leg");
		this.addItem(ItemRegistry.SMOKED_PUFFSHROOM_TENDRIL, "Smoked Puffshroom Tendril");
		this.addItem(ItemRegistry.SMOKED_SILT_CRAB_CLAW, "Smoked Crab Claw");
		this.addItem(ItemRegistry.SMOKED_SNAIL_FLESH, "Smoked Snail Flesh");
		this.addItem(ItemRegistry.RAW_OLM_EGG, "Olm Egg Cluster");
		this.addItem(ItemRegistry.COOKED_OLM_EGG, "Baked Olm Egg Cluster");
		this.addItem(ItemRegistry.OLMLETTE, "Olmlette");
		this.addItem(ItemRegistry.SILK_GRUB, "Silk Grub");
		this.addItem(ItemRegistry.BONE_HELMET, "Bone Helmet");
		this.addItem(ItemRegistry.BONE_CHESTPLATE, "Bone Chestplate");
		this.addItem(ItemRegistry.BONE_LEGGINGS, "Bone Leggings");
		this.addItem(ItemRegistry.BONE_BOOTS, "Bone Boots");
		this.addItem(ItemRegistry.LURKER_SKIN_HELMET, "Lurker Skin Helmet");
		this.addItem(ItemRegistry.LURKER_SKIN_CHESTPLATE, "Lurker Skin Chestplate");
		this.addItem(ItemRegistry.LURKER_SKIN_LEGGINGS, "Lurker Skin Leggings");
		this.addItem(ItemRegistry.LURKER_SKIN_BOOTS, "Lurker Skin Boots");
		this.addItem(ItemRegistry.SYRMORITE_HELMET, "Syrmorite Helmet");
		this.addItem(ItemRegistry.SYRMORITE_CHESTPLATE, "Syrmorite Chestplate");
		this.addItem(ItemRegistry.SYRMORITE_LEGGINGS, "Syrmorite Leggings");
		this.addItem(ItemRegistry.SYRMORITE_BOOTS, "Syrmorite Boots");
		this.addItem(ItemRegistry.VALONITE_HELMET, "Valonite Helmet");
		this.addItem(ItemRegistry.VALONITE_CHESTPLATE, "Valonite Chestplate");
		this.addItem(ItemRegistry.VALONITE_LEGGINGS, "Valonite Leggings");
		this.addItem(ItemRegistry.VALONITE_BOOTS, "Valonite Boots");
		this.addItem(ItemRegistry.ANCIENT_HELMET, "Ancient Helmet");
		this.addItem(ItemRegistry.ANCIENT_CHESTPLATE, "Ancient Chestplate");
		this.addItem(ItemRegistry.ANCIENT_LEGGINGS, "Ancient Leggings");
		this.addItem(ItemRegistry.ANCIENT_BOOTS, "Ancient Boots");
		this.add("item.thebetweenlands.ancient_armor.desc", "Reduces Magic Damage.\nUp to half magic damage reduction with a full set equipped.");
		this.addItem(ItemRegistry.RUBBER_BOOTS, "Rubber Boots");
		this.addItem(ItemRegistry.MARSH_RUNNER_BOOTS, "Boots of the Marsh Runner");

		this.addItem(ItemRegistry.AMATE_MAP, "Empty Amate Map");
		this.addItem(ItemRegistry.FILLED_AMATE_MAP, "Amate Map");
		this.addDisc(ItemRegistry.RECORD_ANCIENT, "Temple Disc", "Voog2 - Ancient");
		this.addDisc(ItemRegistry.RECORD_ASTATOS, "Legendary Disc", "Voog2 - Astatos");
		this.addDisc(ItemRegistry.RECORD_BENEATH_A_GREEN_SKY, "Music Disc", "Voog2 - Beneath A Green Sky");
		this.addDisc(ItemRegistry.RECORD_BETWEEN_YOU_AND_ME, "Tribeman's Disc", "Voog2 - Between You And Me");
		this.addDisc(ItemRegistry.RECORD_CHRISTMAS_ON_THE_MARSH, "Frosty Disc", "Voog2 - Christmas On The Marsh");
		this.addDisc(ItemRegistry.RECORD_DEEP_WATER_THEME, "Deep Water", "Rotch Gwylt - Deep Water");
		this.addDisc(ItemRegistry.RECORD_DJ_WIGHTS_MIXTAPE, "DJ Wight's Hot New Mixtape", "Voog2 - Rave In A Cave");
		this.addDisc(ItemRegistry.RECORD_HAG_DANCE, "Music Disc", "Voog2 - Hag Dance");
		this.addDisc(ItemRegistry.RECORD_LONELY_FIRE, "Music Disc", "Voog2 - Lonely Fire");
		this.addDisc(ItemRegistry.RECORD_ONWARDS, "Music Disc", "Voog2 - Onwards");
		this.addDisc(ItemRegistry.RECORD_STUCK_IN_THE_MUD, "Music Disc", "Voog2 - Stuck In The Mud");
		this.addDisc(ItemRegistry.RECORD_THE_EXPLORER, "Explorer's Disc", "Voog2 - The Explorer");
		this.addDisc(ItemRegistry.RECORD_WANDERING_WISPS, "Music Disc", "Voog2 - Wandering Wisps");
		this.addDisc(ItemRegistry.RECORD_WATERLOGGED, "Music Disc", "Voog2 - Waterlogged");
		this.addDisc(ItemRegistry.MYSTERIOUS_RECORD, "Mysterious Disc", "...");

		this.add("item.thebetweenlands.amate_map.invalid", "Can't create an Amate Map outside of The Betweenlands");

		this.addItem(ItemRegistry.GROUND_LEAF, "Ground Leaf");
		this.addItem(ItemRegistry.GROUND_CATTAIL, "Ground Cattail");
		this.addItem(ItemRegistry.GROUND_SWAMP_GRASS, "Ground Swamp Grass");
		this.addItem(ItemRegistry.GROUND_SHOOTS, "Ground Shoots");
		this.addItem(ItemRegistry.GROUND_ARROW_ARUM, "Ground Arrow Arum");
		this.addItem(ItemRegistry.GROUND_BUTTON_BUSH, "Ground Button Bush");
		this.addItem(ItemRegistry.GROUND_MARSH_HIBUSCUS, "Ground Marsh Hibiscus");
		this.addItem(ItemRegistry.GROUND_PICKERELWEED, "Ground Pickerelweed");
		this.addItem(ItemRegistry.GROUND_SOFT_RUSH, "Ground Soft Rush");
		this.addItem(ItemRegistry.GROUND_MARSH_MALLOW, "Ground Marsh Mallow");
		this.addItem(ItemRegistry.GROUND_MILKWEED, "Ground Milkweed");
		this.addItem(ItemRegistry.GROUND_BLUE_IRIS, "Ground Blue Iris");
		this.addItem(ItemRegistry.GROUND_COPPER_IRIS, "Ground Copper Iris");
		this.addItem(ItemRegistry.GROUND_BLUE_EYED_GRASS, "Ground Blue Eyed Grass");
		this.addItem(ItemRegistry.GROUND_BONESET, "Ground Boneset");
		this.addItem(ItemRegistry.GROUND_BOTTLE_BRUSH_GRASS, "Ground Bottle Brush Grass");
		this.addItem(ItemRegistry.GROUND_WEEDWOOD_BARK, "Ground Weedwood Bark");
		this.addItem(ItemRegistry.GROUND_DRIED_SWAMP_REED, "Ground Dried Swamp Reed");
		this.addItem(ItemRegistry.GROUND_ALGAE, "Ground Algae");
		this.addItem(ItemRegistry.GROUND_ANGLER_TOOTH, "Ground Angler Tooth");
		this.addItem(ItemRegistry.GROUND_BLACKHAT_MUSHROOM, "Ground Blackhat Mushroom");
		this.addItem(ItemRegistry.GROUND_CRIMSON_SNAIL_SHELL, "Ground Crimson Snail Shell");
		this.addItem(ItemRegistry.GROUND_BOG_BEAN, "Ground Bog Bean");
		this.addItem(ItemRegistry.GROUND_BROOMSEDGE, "Ground Broomsedge");
		this.addItem(ItemRegistry.GROUND_BULB_CAPPED_MUSHROOM, "Ground Bulb-Capped Mushroom");
		this.addItem(ItemRegistry.GROUND_CARDINAL_FLOWER, "Ground Cardinal Flower");
		this.addItem(ItemRegistry.GROUND_CAVE_GRASS, "Ground Cave Grass");
		this.addItem(ItemRegistry.GROUND_CAVE_MOSS, "Ground Cave Moss");
		this.addItem(ItemRegistry.GROUND_CRIMSON_MIDDLE_GEM, "Ground Crimson Middle Gem");
		this.addItem(ItemRegistry.GROUND_DEEP_WATER_CORAL, "Ground Deep Water Coral");
		this.addItem(ItemRegistry.GROUND_FLATHEAD_MUSHROOM, "Ground Flathead Mushroom");
		this.addItem(ItemRegistry.GROUND_GOLDEN_CLUB, "Ground Golden Club");
		this.addItem(ItemRegistry.GROUND_GREEN_MIDDLE_GEM, "Ground Green Middle Gem");
		this.addItem(ItemRegistry.GROUND_HANGER, "Ground Hanger");
		this.addItem(ItemRegistry.GROUND_LICHEN, "Ground Lichen");
		this.addItem(ItemRegistry.GROUND_MARSH_MARIGOLD, "Ground Marsh Marigold");
		this.addItem(ItemRegistry.GROUND_MIRE_CORAL, "Ground Mire Coral");
		this.addItem(ItemRegistry.GROUND_OCHRE_SNAIL_SHELL, "Ground Ochre Snail Shell");
		this.addItem(ItemRegistry.GROUND_MOSS, "Ground Moss");
		this.addItem(ItemRegistry.GROUND_NETTLE, "Ground Nettle");
		this.addItem(ItemRegistry.GROUND_PHRAGMITES, "Ground Phragmites");
		this.addItem(ItemRegistry.GROUND_SLUDGECREEP, "Ground Sludgecreep");
		this.addItem(ItemRegistry.GROUND_SUNDEW, "Ground Sundew");
		this.addItem(ItemRegistry.GROUND_SWAMP_KELP, "Ground Swamp Kelp");
		this.addItem(ItemRegistry.GROUND_ROOTS, "Ground Roots");
		this.addItem(ItemRegistry.GROUND_AQUA_MIDDLE_GEM, "Ground Aqua Middle Gem");
		this.addItem(ItemRegistry.GROUND_PITCHER_PLANT, "Ground Pitcher Plant");
		this.addItem(ItemRegistry.GROUND_WATER_WEEDS, "Ground Water Weeds");
		this.addItem(ItemRegistry.GROUND_VENUS_FLY_TRAP, "Ground Venus Fly Trap");
		this.addItem(ItemRegistry.GROUND_VOLARPAD, "Ground Volarpad");
		this.addItem(ItemRegistry.GROUND_THORNS, "Ground Thorns");
		this.addItem(ItemRegistry.GROUND_POISON_IVY, "Ground Poison Ivy");
		this.addItem(ItemRegistry.GROUND_BLADDERWORT_FLOWER, "Ground Bladderwort Flower");
		this.addItem(ItemRegistry.GROUND_BLADDERWORT_STALK, "Ground Bladderwort Stalk");
		this.addItem(ItemRegistry.GROUND_EDGE_SHROOM, "Ground Edge Shroom");
		this.addItem(ItemRegistry.GROUND_EDGE_MOSS, "Ground Edge Moss");
		this.addItem(ItemRegistry.GROUND_EDGE_LEAF, "Ground Edge Leaf");
		this.addItem(ItemRegistry.GROUND_ROTBULB, "Ground Rotbulb");
		this.addItem(ItemRegistry.GROUND_PALE_GRASS, "Ground Pale Grass");
		this.addItem(ItemRegistry.GROUND_STRING_ROOTS, "Ground String Roots");
		this.addItem(ItemRegistry.GROUND_CRYPTWEED, "Ground Cryptweed");
		this.addItem(ItemRegistry.GROUND_BETWEENSTONE_PEBBLE, "Ground Betweenstone Pebble");
		this.addItem(ItemRegistry.LEAF, "Leaf");
		this.addItem(ItemRegistry.ALGAE_CLUMP, "Algae Clump");
		this.addItem(ItemRegistry.ARROW_ARUM_LEAF, "Arrow Arum Leaf");
		this.addItem(ItemRegistry.BLUE_EYED_GRASS_FLOWERS, "Blue Eyed Grass Flowers");
		this.addItem(ItemRegistry.BLUE_IRIS_PETAL, "Blue Iris Petals");
		this.addItem(ItemRegistry.MIRE_CORAL_STALK, "Mire Coral Stalk");
		this.addItem(ItemRegistry.DEEP_WATER_CORAL_STALK, "Deep Water Coral Stalk");
		this.addItem(ItemRegistry.BOG_BEAN_FLOWER_DROP, "Bog Bean Flower");
		this.addItem(ItemRegistry.BONESET_FLOWERS, "Boneset Flowers");
		this.addItem(ItemRegistry.BOTTLE_BRUSH_GRASS_BLADES, "Bottle Brush Grass Blades");
		this.addItem(ItemRegistry.BROOMSEDGE_LEAVES, "Broomsedge Leaves");
		this.addItem(ItemRegistry.BUTTON_BUSH_FLOWERS, "Button Bush Flowers");
		this.addItem(ItemRegistry.CARDINAL_FLOWER_PETALS, "Cardinal Flower Petals");
		this.addItem(ItemRegistry.CATTAIL_HEAD, "Cattail Head");
		this.addItem(ItemRegistry.CAVE_GRASS_BLADES, "Cave Grass Blades");
		this.addItem(ItemRegistry.COPPER_IRIS_PETALS, "Copper Iris Blades");
		this.addItem(ItemRegistry.GOLDEN_CLUB_FLOWERS, "Golden Club Flowers");
		this.addItem(ItemRegistry.LICHEN_CLUMP, "Lichen Clump");
		this.addItem(ItemRegistry.MARSH_HIBISCUS_FLOWER, "Marsh Hibiscus Flower");
		this.addItem(ItemRegistry.MARSH_MALLOW_FLOWER, "Marsh Mallow Flower");
		this.addItem(ItemRegistry.MARSH_MARIGOLD_FLOWER_DROP, "Marsh Marigold Flower");
		this.addItem(ItemRegistry.NETTLE_LEAF, "Nettle Leaf");
		this.addItem(ItemRegistry.PHRAGMITE_STEMS, "Phragmite Stems");
		this.addItem(ItemRegistry.PICKERELWEED_FLOWER, "Pickerelweed Flower");
		this.addItem(ItemRegistry.SHOOT_LEAVES, "Shoot Leaves");
		this.addItem(ItemRegistry.SLUDGECREEP_LEAVES, "Sludgecreep Leaves");
		this.addItem(ItemRegistry.SOFT_RUSH_LEAVES, "Soft Rush Leaves");
		this.addItem(ItemRegistry.SUNDEW_HEAD, "Sundew Head");
		this.addItem(ItemRegistry.SWAMP_GRASS_BLADES, "Swamp Grass Blades");
		this.addItem(ItemRegistry.CAVE_MOSS_CLUMP, "Cave Moss Clump");
		this.addItem(ItemRegistry.MOSS_CLUMP, "Moss Clump");
		this.addItem(ItemRegistry.MILKWEED_FLOWER, "Milkweed Flower");
		this.addItem(ItemRegistry.HANGER_DROP, "Hanger");
		this.addItem(ItemRegistry.PITCHER_PLANT_TRAP, "Pitcher Plant Trap");
		this.addItem(ItemRegistry.WATER_WEEDS_DROP, "Water Weeds");
		this.addItem(ItemRegistry.VENUS_FLY_TRAP_HEAD, "Venus Fly Trap Head");
		this.addItem(ItemRegistry.VOLARPAD_LEAF, "Volarpad Leaf");
		this.addItem(ItemRegistry.THORN_BRANCH, "Thorn Branch");
		this.addItem(ItemRegistry.POISON_IVY_LEAF, "Poison Ivy Leaf");
		this.addItem(ItemRegistry.BLADDERWORT_STALK_DROP, "Bladderwort Stalk");
		this.addItem(ItemRegistry.BLADDERWORT_FLOWER_DROP, "Bladderwort Flower");
		this.addItem(ItemRegistry.EDGE_SHROOM_GILLS, "Edge Shroom Gills");
		this.addItem(ItemRegistry.EDGE_MOSS_CLUMP, "Edge Moss Clump");
		this.addItem(ItemRegistry.EDGE_LEAF_DROP, "Edge Leaf");
		this.addItem(ItemRegistry.ROTBULB_STALK, "Rotbulb Stalk");
		this.addItem(ItemRegistry.PALE_GRASS_BLADES, "Pale Grass Blades");
		this.addItem(ItemRegistry.STRING_ROOT_FIBERS, "String Root Fibers");
		this.addItem(ItemRegistry.CRYPTWEED_BLADES, "Cryptweed Blades");

		this.addAspect(AspectRegistry.ARMANIIS, "Desire", "Has effect on the desires of a mob or the player. Could be useful for food, but also things like trading or corrupting the desire.");
		this.addAspect(AspectRegistry.AZUWYNN, "Muscle", "Has effect on the muscles, could either result in more damage, speed or maybe rapid fire and all stuff in that regard.");
		this.addAspect(AspectRegistry.BYARIIS, "Corruption", "This effect can corrupt other effects, but even corrupt effects. So it could turn negative into positive, and positive into negative. so for example, if this effect gets combined with health it will do something negative to your health, but if this effect gets combined twice with health, it will corrupt itself and thus do something positive.");
		this.addAspect(AspectRegistry.BYRGINAZ, "Water", "Magical property which relates to water. Any combination with this effect can be related to water.");
		this.addAspect(AspectRegistry.CELAWYNN, "Stomach", "Has effect on the stomach. So this could have effect on the hunger bar for example.");
		this.addAspect(AspectRegistry.DAYUNIIS, "Mind", "Has effect on the player's mind and on how senses work. Could be positive, or negative (think nausea/schizophrenia).");
		this.addAspect(AspectRegistry.FERGALAZ, "Earth", "Magical property which relates to earth. Any combination with this effect can be related to the element earth.");
		this.addAspect(AspectRegistry.FIRNALAZ, "Fire", "Magical property which relates to fire. Any combination with this effect can be related to fire.");
		this.addAspect(AspectRegistry.FREIWYNN, "Vision", "Alters the player's vision. (In combination with other properties. So for example when you combine health with vision, you would be able to spot mobs their health.)");
		this.addAspect(AspectRegistry.GEOLIIRGAZ, "Void", "Magical property which relates to the void or ether. Any combination with this effect can be related to void or darkness.");
		this.addAspect(AspectRegistry.ORDANIIS, "Enchance", "Needs new description");
		this.addAspect(AspectRegistry.UDURIIS, "Chaos", "The aspect that correlates to the natural orderless state of the universe.");
		this.addAspect(AspectRegistry.WODREN, "Soul", "The aspect that affects the spiritual state and life force of a being.");
		this.addAspect(AspectRegistry.YEOWYNN, "Health", "Has effect on the health bar, could be both negative or positive, depending on the combination.");
		this.addAspect(AspectRegistry.YIHINREN, "Form", "This effect has influence on the form of things, both physical and psychological. A very rare aspect that is mainly used in the special potions.");
		this.addAspect(AspectRegistry.YUNUGAZ, "Wind", "Magical property which relates to wind. Any combination with this effect can be related to the element wind.");
	}

	private void addItemWithDesc(DeferredItem<Item> item, String name, String desc) {
		this.addItem(item, name);
		this.add(item.get().getDescriptionId() + ".desc", desc);
	}

	private void addBlockWithDesc(DeferredBlock<Block> block, String name, String desc) {
		this.addBlock(block, name);
		this.add(block.get().getDescriptionId() + ".desc", desc);
	}

	private void addDisc(DeferredItem<Item> disc, String name, String desc) {
		this.addItem(disc, name);
		this.add(Util.makeDescriptionId("jukebox_song", disc.get().components().get(DataComponents.JUKEBOX_PLAYABLE).song().key().location()), desc);
	}

	private void addAspect(ResourceKey<AspectType> aspect, String manualType, String desc) {
		String base = Util.makeDescriptionId("aspect", aspect.location());
		this.add(base, StringUtils.capitalize(aspect.location().getPath()));
		this.add(base + ".manual", manualType);
		this.add(base + ".desc", desc);
	}
}
