package thebetweenlands.common.registries;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import thebetweenlands.common.TheBetweenlands;
import thebetweenlands.common.block.entity.*;
import thebetweenlands.common.block.entity.simulacrum.SimulacrumBlockEntity;
import thebetweenlands.common.block.entity.spawner.MobSpawnerBlockEntity;

public class BlockEntityRegistry {
	public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES = DeferredRegister.create(Registries.BLOCK_ENTITY_TYPE, TheBetweenlands.ID);

	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<WispBlockEntity>> WISP = BLOCK_ENTITIES.register("wisp", () -> BlockEntityType.Builder.of(WispBlockEntity::new, BlockRegistry.WISP.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<LootPotBlockEntity>> LOOT_POT = BLOCK_ENTITIES.register("loot_pot", () -> BlockEntityType.Builder.of(LootPotBlockEntity::new, BlockRegistry.LOOT_POT_1.get(), BlockRegistry.LOOT_POT_2.get(), BlockRegistry.LOOT_POT_3.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MobSpawnerBlockEntity>> MOB_SPAWNER = BLOCK_ENTITIES.register("mob_spawner", () -> BlockEntityType.Builder.of(MobSpawnerBlockEntity::new, BlockRegistry.MOB_SPAWNER.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<LootUrnBlockEntity>> LOOT_URN = BLOCK_ENTITIES.register("loot_urn", () -> BlockEntityType.Builder.of(LootUrnBlockEntity::new, BlockRegistry.LOOT_URN_1.get(), BlockRegistry.LOOT_URN_2.get(), BlockRegistry.LOOT_URN_3.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SpikeTrapBlockEntity>> SPIKE_TRAP = BLOCK_ENTITIES.register("spike_trap", () -> BlockEntityType.Builder.of(SpikeTrapBlockEntity::new, BlockRegistry.SPIKE_TRAP.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<PossessedBlockEntity>> POSSESSED_BLOCK = BLOCK_ENTITIES.register("possessed_block", () -> BlockEntityType.Builder.of(PossessedBlockEntity::new, BlockRegistry.POSSESSED_BLOCK.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ItemCageBlockEntity>> ITEM_CAGE = BLOCK_ENTITIES.register("item_cage", () -> BlockEntityType.Builder.of(ItemCageBlockEntity::new, BlockRegistry.ITEM_CAGE.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<ItemShelfBlockEntity>> ITEM_SHELF = BLOCK_ENTITIES.register("item_shelf", () -> BlockEntityType.Builder.of(ItemShelfBlockEntity::new, BlockRegistry.ITEM_SHELF.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<PuffshroomBlockEntity>> PUFFSHROOM = BLOCK_ENTITIES.register("puffshroom", () -> BlockEntityType.Builder.of(PuffshroomBlockEntity::new, BlockRegistry.PUFFSHROOM.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<BeamOriginBlockEntity>> BEAM_ORIGIN = BLOCK_ENTITIES.register("beam_origin", () -> BlockEntityType.Builder.of(BeamOriginBlockEntity::new, BlockRegistry.BEAM_ORIGIN.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<BeamRelayBlockEntity>> BEAM_RELAY = BLOCK_ENTITIES.register("beam_relay", () -> BlockEntityType.Builder.of(BeamRelayBlockEntity::new, BlockRegistry.BEAM_RELAY.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MudBrickAlcoveBlockEntity>> MUD_BRICK_ALCOVE = BLOCK_ENTITIES.register("mud_brick_alcove", () -> BlockEntityType.Builder.of(MudBrickAlcoveBlockEntity::new, BlockRegistry.MUD_BRICK_ALCOVE.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DungeonDoorRunesBlockEntity>> DUNGEON_DOOR_RUNES = BLOCK_ENTITIES.register("dungeon_door_runes", () -> BlockEntityType.Builder.of(DungeonDoorRunesBlockEntity::new, BlockRegistry.DUNGEON_DOOR_RUNES.get(), BlockRegistry.MIMIC_DUNGEON_DOOR_RUNES.get(), BlockRegistry.CRAWLER_DUNGEON_DOOR_RUNES.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DungeonDoorCombinationBlockEntity>> DUNGEON_DOOR_COMBINATION = BLOCK_ENTITIES.register("dungeon_door_combination", () -> BlockEntityType.Builder.of(DungeonDoorCombinationBlockEntity::new, BlockRegistry.DUNGEON_DOOR_COMBINATION.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DecayPitGroundChainBlockEntity>> DECAY_PIT_GROUND_CHAIN = BLOCK_ENTITIES.register("decay_pit_ground_chain", () -> BlockEntityType.Builder.of(DecayPitGroundChainBlockEntity::new, BlockRegistry.DECAY_PIT_GROUND_CHAIN.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DecayPitHangingChainBlockEntity>> DECAY_PIT_HANGING_CHAIN = BLOCK_ENTITIES.register("decay_pit_hanging_chain", () -> BlockEntityType.Builder.of(DecayPitHangingChainBlockEntity::new, BlockRegistry.DECAY_PIT_HANGING_CHAIN.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DecayPitControlBlockEntity>> DECAY_PIT_CONTROL = BLOCK_ENTITIES.register("decay_pit_control", () -> BlockEntityType.Builder.of(DecayPitControlBlockEntity::new, BlockRegistry.DECAY_PIT_CONTROL.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<PresentBlockEntity>> PRESENT = BLOCK_ENTITIES.register("present", () -> BlockEntityType.Builder.of(PresentBlockEntity::new,
		BlockRegistry.WHITE_PRESENT.get(), BlockRegistry.LIGHT_BLUE_PRESENT.get(), BlockRegistry.GRAY_PRESENT.get(), BlockRegistry.BLACK_PRESENT.get(),
		BlockRegistry.RED_PRESENT.get(), BlockRegistry.ORANGE_PRESENT.get(), BlockRegistry.YELLOW_PRESENT.get(), BlockRegistry.GREEN_PRESENT.get(),
		BlockRegistry.LIME_PRESENT.get(), BlockRegistry.BLUE_PRESENT.get(), BlockRegistry.CYAN_PRESENT.get(), BlockRegistry.LIGHT_BLUE_PRESENT.get(),
		BlockRegistry.PURPLE_PRESENT.get(), BlockRegistry.MAGENTA_PRESENT.get(), BlockRegistry.PINK_PRESENT.get(), BlockRegistry.BROWN_PRESENT.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DugSoilBlockEntity>> DUG_SOIL = BLOCK_ENTITIES.register("dug_soil", () -> BlockEntityType.Builder.of(DugSoilBlockEntity::new, BlockRegistry.DUG_SWAMP_DIRT.get(), BlockRegistry.DUG_SWAMP_GRASS.get(), BlockRegistry.PURIFIED_DUG_SWAMP_DIRT.get(), BlockRegistry.PURIFIED_DUG_SWAMP_GRASS.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<DruidAltarBlockEntity>> DRUID_ALTAR = BLOCK_ENTITIES.register("druid_altar", () -> BlockEntityType.Builder.of(DruidAltarBlockEntity::new, BlockRegistry.DRUID_ALTAR.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<PurifierBlockEntity>> PURIFIER = BLOCK_ENTITIES.register("purifier", () -> BlockEntityType.Builder.of(PurifierBlockEntity::new, BlockRegistry.PURIFIER.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<WeedwoodCraftingTableBlockEntity>> WEEDWOOD_CRAFTING_TABLE = BLOCK_ENTITIES.register("weedwood_crafting_table", () -> BlockEntityType.Builder.of(WeedwoodCraftingTableBlockEntity::new, BlockRegistry.WEEDWOOD_CRAFTING_TABLE.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<CompostBinBlockEntity>> COMPOST_BIN = BLOCK_ENTITIES.register("compost_bin", () -> BlockEntityType.Builder.of(CompostBinBlockEntity::new, BlockRegistry.COMPOST_BIN.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SulfurFurnaceBlockEntity>> SULFUR_FURNACE = BLOCK_ENTITIES.register("sulfur_furnace", () -> BlockEntityType.Builder.of(SulfurFurnaceBlockEntity::new, BlockRegistry.SULFUR_FURNACE.get(), BlockRegistry.DUAL_SULFUR_FURNACE.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<RubberTapBlockEntity>> RUBBER_TAP = BLOCK_ENTITIES.register("rubber_tap", () -> BlockEntityType.Builder.of(RubberTapBlockEntity::new, BlockRegistry.WEEDWOOD_RUBBER_TAP.get(), BlockRegistry.SYRMORITE_RUBBER_TAP.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SyrmoriteHopperBlockEntity>> SYRMORITE_HOPPER = BLOCK_ENTITIES.register("syrmorite_hopper", () -> BlockEntityType.Builder.of(SyrmoriteHopperBlockEntity::new, BlockRegistry.SYRMORITE_HOPPER.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MudFlowerPotBlockEntity>> MUD_FLOWER_POT = BLOCK_ENTITIES.register("mud_flower_pot", () -> BlockEntityType.Builder.of(MudFlowerPotBlockEntity::new, BlockRegistry.MUD_FLOWER_POT.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<GeckoCageBlockEntity>> GECKO_CAGE = BLOCK_ENTITIES.register("gecko_cage", () -> BlockEntityType.Builder.of(GeckoCageBlockEntity::new, BlockRegistry.GECKO_CAGE.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<InfuserBlockEntity>> INFUSER = BLOCK_ENTITIES.register("infuser", () -> BlockEntityType.Builder.of(InfuserBlockEntity::new, BlockRegistry.INFUSER.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<AspectVialBlockEntity>> ASPECT_VIAL = BLOCK_ENTITIES.register("aspect_vial", () -> BlockEntityType.Builder.of(AspectVialBlockEntity::new, BlockRegistry.ORANGE_ASPECT_VIAL.get(), BlockRegistry.GREEN_ASPECT_VIAL.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MortarBlockEntity>> MORTAR = BLOCK_ENTITIES.register("mortar", () -> BlockEntityType.Builder.of(MortarBlockEntity::new, BlockRegistry.MORTAR.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<CenserBlockEntity>> CENSER = BLOCK_ENTITIES.register("censer", () -> BlockEntityType.Builder.of(CenserBlockEntity::new, BlockRegistry.CENSER.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<BarrelBlockEntity>> BARREL = BLOCK_ENTITIES.register("barrel", () -> BlockEntityType.Builder.of(BarrelBlockEntity::new, BlockRegistry.WEEDWOOD_BARREL.get(), BlockRegistry.SYRMORITE_BARREL.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<AnimatorBlockEntity>> ANIMATOR = BLOCK_ENTITIES.register("censer", () -> BlockEntityType.Builder.of(AnimatorBlockEntity::new, BlockRegistry.ANIMATOR.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<AlembicBlockEntity>> ALEMBIC = BLOCK_ENTITIES.register("alembic", () -> BlockEntityType.Builder.of(AlembicBlockEntity::new, BlockRegistry.ALEMBIC.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MossBedBlockEntity>> MOSS_BED = BLOCK_ENTITIES.register("moss_bed", () -> BlockEntityType.Builder.of(MossBedBlockEntity::new, BlockRegistry.MOSS_BED.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<RepellerBlockEntity>> REPELLER = BLOCK_ENTITIES.register("repeller", () -> BlockEntityType.Builder.of(RepellerBlockEntity::new, BlockRegistry.REPELLER.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<WaystoneBlockEntity>> WAYSTONE = BLOCK_ENTITIES.register("waystone", () -> BlockEntityType.Builder.of(WaystoneBlockEntity::new, BlockRegistry.WAYSTONE.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<GroundItemBlockEntity>> GROUND_ITEM = BLOCK_ENTITIES.register("ground_item", () -> BlockEntityType.Builder.of(GroundItemBlockEntity::new, BlockRegistry.GROUND_ITEM.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SimulacrumBlockEntity>> SIMULACRUM = BLOCK_ENTITIES.register("simulacrum", () -> BlockEntityType.Builder.of(SimulacrumBlockEntity::new,
		BlockRegistry.DEEPMAN_SIMULACRUM_1.get(), BlockRegistry.DEEPMAN_SIMULACRUM_2.get(), BlockRegistry.DEEPMAN_SIMULACRUM_3.get(),
		BlockRegistry.LAKE_CAVERN_SIMULACRUM_1.get(), BlockRegistry.LAKE_CAVERN_SIMULACRUM_2.get(), BlockRegistry.LAKE_CAVERN_SIMULACRUM_3.get(),
		BlockRegistry.ROOTMAN_SIMULACRUM_1.get(), BlockRegistry.ROOTMAN_SIMULACRUM_2.get(), BlockRegistry.ROOTMAN_SIMULACRUM_3.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<OfferingTableBlockEntity>> OFFERING_TABLE = BLOCK_ENTITIES.register("offering_table", () -> BlockEntityType.Builder.of(OfferingTableBlockEntity::new, BlockRegistry.OFFERING_TABLE.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<WindChimeBlockEntity>> WIND_CHIME = BLOCK_ENTITIES.register("offering_table", () -> BlockEntityType.Builder.of(WindChimeBlockEntity::new, BlockRegistry.WIND_CHIME.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<FishingTackleBoxBlockEntity>> FISHING_TACKLE_BOX = BLOCK_ENTITIES.register("fishing_tackle_box", () -> BlockEntityType.Builder.of(FishingTackleBoxBlockEntity::new, BlockRegistry.FISHING_TACKLE_BOX.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SmokingRackBlockEntity>> SMOKING_RACK = BLOCK_ENTITIES.register("smoking_rack", () -> BlockEntityType.Builder.of(SmokingRackBlockEntity::new, BlockRegistry.SMOKING_RACK.get()).build(null));
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<FishTrimmingTableBlockEntity>> FISH_TRIMMING_TABLE = BLOCK_ENTITIES.register("fish_trimming_table", () -> BlockEntityType.Builder.of(FishTrimmingTableBlockEntity::new, BlockRegistry.FISH_TRIMMING_TABLE.get()).build(null));

}
