@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.common.entities.fishing.anadia;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;