@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.client.renderer.shader;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;