@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.common.component.entity;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;