@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.client.shader.postprocessing;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;