@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package thebetweenlands.api.entity.spawning;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;