name: Build Workflow

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: chmod +x .github/workflows/scripts/test.sh
    - run: ./.github/workflows/scripts/test.sh
      env:
        SECRET_TEST: ${{ secrets.SECRET_TEST }}
#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew build
