name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Setting up environment
      run: |
        chmod +x ".github/workflows/build/setup.sh
        ."/.github/workflows/build/setup.sh"
      env:
        BS_DECR_KEY_SECRET: ${{ secrets.DECR_KEY_SECRET }}
        BS_PULL_REQUEST: 'false'
        
    - name: Building
      run: |
        chmod +x ".github/workflows/${GITHUB_WORKFLOW}/build.sh"
        ."/.github/workflows/${GITHUB_WORKFLOW}/build.sh"
      env:
        BS_DECR_KEY_SECRET: ${{ secrets.DECR_KEY_SECRET }}
        BS_PULL_REQUEST: 'false'
        
    - name: Deploying
      run: |
        chmod +x ".github/workflows/${GITHUB_WORKFLOW}/deploy.sh"
        ."/.github/workflows/${GITHUB_WORKFLOW}/deploy.sh"
      env:
        BS_DECR_KEY_SECRET: ${{ secrets.DECR_KEY_SECRET }}
        BS_PULL_REQUEST: 'false'
