name: discord_bot

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 20
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Getting index revisions
      run: |
        INDEX_FILE='index.json'
        
        CURRENT_INDEX_REVISION=$(git show $(git log --abbrev=0 --format=%H --skip=0 --max-count=1 ${INDEX_FILE}):${INDEX_FILE})
        echo "Current index:"
        echo "$(echo """$CURRENT_INDEX_REVISION""" | tail --bytes=1000)"
        
        echo 'CURRENT_INDEX_REVISION<<CURRENT_INDEX_REVISION_EOF' >> $GITHUB_ENV
        echo "$CURRENT_INDEX_REVISION" >> $GITHUB_ENV
        echo 'CURRENT_INDEX_REVISION_EOF' >> $GITHUB_ENV
        
        PREVIOUS_INDEX_REVISION=$(git show $(git log --abbrev=0 --format=%H --skip=1 --max-count=1 ${INDEX_FILE}):${INDEX_FILE})
        echo "Previous index:"
        echo "$(echo """$PREVIOUS_INDEX_REVISION""" | tail --bytes=1000)"
        
        echo 'PREVIOUS_INDEX_REVISION<<PREVIOUS_INDEX_REVISION_EOF' >> $GITHUB_ENV
        echo "$PREVIOUS_INDEX_REVISION" >> $GITHUB_ENV
        echo 'PREVIOUS_INDEX_REVISION_EOF' >> $GITHUB_ENV
        
    - name: Building
      run: ./discord_bot/gradlew build
        
    - name: Running
      run: java -jar "discord_bot/build/libs/Discord Gallery Bot-1.0.jar"
      env:
        DISCORD_CHANNEL_ID: '614072971291525130'
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_GALLERY_BOT_TOKEN }}
